Add prompter interface
airplanedev/cli pull request #1011
Opened 2023-03-13 22:35 UTC by calufornia

## Description

## Test plan

2023-03-13 22:35 UTC, calufornia commented
Current dependencies on/for this PR:
* main
  * **PR #1009** <a href="https://app.graphite.dev/github/pr/airplanedev/cli/1009" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #1011** <a href="https://app.graphite.dev/github/pr/airplanedev/cli/1011" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/airplanedev/cli/1011?utm_source=stack-comment).

2023-03-14 14:18 UTC, leeweisberger requested changes

2023-03-14 14:18 UTC, leeweisberger commented on pkg/prompts/survey.go
> +type Surveyor struct{}
Add

var _ Prompter = Surveyor{}

This should provide a compile time check in this file that surveyor implements prompter

2023-03-14 14:18 UTC, leeweisberger commented on pkg/prompts/prompts.go
> +	return WithDefault(false)
Can we just delete these and use WithDefault?

2023-03-14 14:18 UTC, leeweisberger commented on pkg/prompts/prompts.go
> +func WithSecret() Opt {
Can you add comments to all these? I'm not sure what all of them do personally

2023-03-14 14:18 UTC, leeweisberger commented on pkg/prompts/prompts.go
> +func WithRedirectStdOutToErr() Opt {
What exactly does this do? Why would I set this? it seems like we set this most of the time. Is there are reason we don't set it all of the time?

2023-03-15 03:46 UTC, calufornia commented on pkg/prompts/prompts.go
> +func WithRedirectStdOutToErr() Opt {
I just wanted to make this PR as much of a no-op as possible. I think we can set it all the time, I will go ahead and do that

2023-03-15 15:36 UTC, leeweisberger approved these changes

2023-03-15 15:36 UTC, leeweisberger commented on pkg/prompts/prompts.go
> +func WithRedirectStdOutToErr() Opt {
If we want to set it all the time, we can just default it to true and then nobody has to set it.

2023-03-15 19:50 UTC, merged