Add dev server endpoint to generate and write SQL task
airplanedev/cli pull request #1017
Opened 2023-03-16 15:58 UTC by calufornia

## Description

Adds an endpoint, `/dev/autopilot/generate`, that generates the contents for a SQL task and writes two files: the SQL entrypoint and the task definition yaml. 

Resolves DTS-446

## Test plan
Verified locally with frontend changes.

2023-03-17 19:32 UTC, ameyakhare requested changes

2023-03-17 19:32 UTC, ameyakhare commented on pkg/server/apidev/autopilot.go
> +	CreateSQLTask       GenerateType = "create-sql-task"
I feel like it might be better to abstract this as action, subject, subject type instead of these permutations of things

ie action: create/insert
subject type: view/task
subject: sql, etc.

2023-03-17 19:32 UTC, ameyakhare commented on pkg/server/apidev/autopilot.go
> +			"Generate a task definition YAML with slug %s, entrypoint %s, and resource slug %s and only return YAML without any prefixes or postfixes in your answer. Name and description should not be empty."
we discussed this offline but this prompt should contain everything necessary except shaping commands (ie name and description should not be empty, remove pre/post fixes) I think these should just be added to the backend prompt generation and this should be as simple as possible.

2023-03-20 18:50 UTC, calufornia commented on pkg/server/apidev/autopilot.go
> +			"Generate a task definition YAML with slug %s, entrypoint %s, and resource slug %s and only return YAML without any prefixes or postfixes in your answer. Name and description should not be empty."
Yep, I'll just remove the TODO for now and move the shaping commands in separate PR.

2023-03-20 18:51 UTC, calufornia commented on pkg/server/apidev/autopilot.go
> +	slug := fmt.Sprintf("my_sql_task_%s", rand)
Yeah, that's probably better—I'll add a TODO for now

2023-03-20 20:03 UTC, ameyakhare approved these changes

2023-03-20 20:03 UTC, ameyakhare commented on pkg/server/apidev/autopilot.go
> +	if autopilotContext.Action == Create && autopilotContext.Subject == Task && autopilotContext.SubjectKind == SQL {
would be nice to put this in some sort of validator class/func instead of just a long conditional, but leaving that up to you

2023-03-20 20:53 UTC, merged