Use build tools package.json for views local dev dependencies
airplanedev/cli pull request #1020
Opened 2023-03-17 16:06 UTC by calufornia

## Description

Reads dev dependencies for local views dev from our build tools package.json, which includes an upgrade to Vite. Also changes some of the typing to use `build.PackageJSON` instead, which is cleaner. Adds tests.

Resolves DTS-213

## Test plan
Tested developing a view locally.

2023-03-17 16:09 UTC, leeweisberger requested changes

2023-03-17 16:09 UTC, leeweisberger commented on pkg/views/dev.go
> +		"vite":                 "4.2.0",
I was gonna do this, but instead of this change, can you import `BuildToolsPackageJSON` from lib and then read package versions from there? We should be using the same package versions when building as when devving

2023-03-17 20:39 UTC, calufornia commented on pkg/views/dev.go
> +	addMissingDeps(defaultDeps, existingDeps, deps, false)
The logic to not override the user's dependencies still exists.

2023-03-21 19:36 UTC, leeweisberger approved these changes

2023-04-03 19:10 UTC, merged