Add insertion support to dev server
airplanedev/cli pull request #1028
Opened 2023-03-22 19:28 UTC by calufornia

## Description

Adds support for generating a view component—the dev server takes the user's current cursor position and inserts an `{{INSERT}}` block that we tell the model to replace with a component. Also moves the `autopilot` code into its own package, reorganizes some code, and adds some missing types.

Resolves DTS-447

## Test plan
Verified in conjunction with web + api changes

2023-03-23 22:24 UTC, ameyakhare requested changes
just have some questions about the prompting style and indentation strategy

2023-03-23 22:24 UTC, ameyakhare commented on pkg/server/autopilot/insert.go
> +	builder.WriteString(fmt.Sprintf("Replace %s with a %s component that %s. ONLY return the generated component.", insertBlock, context.Kind, prompt))
I feel like this prompt insertion may not make sense depending on what the user writes?

2023-03-23 22:24 UTC, ameyakhare commented on pkg/server/autopilot/insert.go
> +	for i, c := range line {
what if they use tabs?

2023-03-24 15:38 UTC, calufornia commented on pkg/server/autopilot/insert.go
> +	for i, c := range line {
CodeMirror by default seems to convert tabs into spaces—so we should be able to use this for now. I'll add a TODO

2023-03-27 22:02 UTC, merged