Add file patching endpoint to dev server
airplanedev/cli pull request #1057
Opened 2023-04-13 21:34 UTC by calufornia

## Description

Adds a new endpoint, `/dev/files/patch`, to the dev server that will be used to patch files in the user's development root. It takes in a set of [unified diffs](https://en.wikipedia.org/wiki/Diff#:~:text=syntax%20highlighting.-,Unified%20format,-%5Bedit%5D) (as strings), and uses the gitdiff package to parse the diffs and apply them. Also moves all the files handlers to their own file.

## Test plan
Verified locally with a test patch.

2023-04-14 17:31 UTC, ameyakhare requested changes
have some questions

2023-04-14 17:31 UTC, ameyakhare commented on pkg/server/files/patch.go
> +		if err := Patch(s, patch); err != nil {
is each patch on a per-file basis? you can't apply multiple patches to the same file right? or does that work properly, even if applying one patch changes the state of the file and may invalidate the other patches?

2023-04-14 17:31 UTC, ameyakhare commented on pkg/server/files/patch.go
> +	diffs, _, err := gitdiff.Parse(patchReader)
does this require that the user has git installed? is this making any git sys calls?

2023-04-14 17:31 UTC, ameyakhare commented on pkg/server/files/patch.go
> +		err = gitdiff.Apply(&output, f, diff)
ditto

2023-04-14 20:05 UTC, calufornia commented on pkg/server/files/patch.go
> +	diffs, _, err := gitdiff.Parse(patchReader)
Nope it doesn't—it's basically a reimplementation of what git diff is doing: https://github.com/bluekeyes/go-gitdiff/blob/master/go.mod

2023-04-14 20:07 UTC, calufornia commented on pkg/server/files/patch.go
> +		if err := Patch(s, patch); err != nil {
A file should be referenced by at most one patch (OTOH, a patch may reference multiple files), so nope it shouldn't invalidate other patches.

2023-04-17 16:35 UTC, ameyakhare approved these changes

2023-04-18 14:24 UTC, merged