Add task init endpoint
airplanedev/cli pull request #1085
Opened 2023-04-20 18:16 UTC by francescaleung

## Description

Supports ASM-284.

## Test plan

Tested locally with web changes

2023-04-20 22:22 UTC, colinking requested changes

2023-04-20 22:22 UTC, colinking commented on pkg/initcmd/initcmd.go
> +	filenamesWithStatus := make([]FilenameWithStatus, len(filenames))
Minor nit, but I'm tempted to lint against pre-initializing slice lengths (or at least lint against not specifying the length). Would you be against that? haha

It's one of those pre-optimizations that very rarely makes a meaningful difference and can easily be wrong (e.g. calling append on `filenamesWithStatus` does not work unless you switch to `make(..., 0, len(...))`)

2023-04-20 22:22 UTC, colinking commented on pkg/initcmd/initcmd.go
> +	filenamesWithStatus := make([]FilenameWithStatus, len(filenames))
Just found https://github.com/ashanbrown/makezero -- what would you think if I enabled that with `-always`?

2023-04-20 22:22 UTC, colinking commented on pkg/server/apidev/apidev.go
> +	r.Handle("/views/init", handlers.WithBody(s, InitViewHandler)).Methods("POST", "OPTIONS")
Can you call these `/tasks|views/create` to align with airport?

2023-04-20 22:22 UTC, colinking commented on pkg/server/apidev/init.go
> +		return InitTaskResponse{}, errors.Wrap(err, "error initializing task")
```suggestion
		return InitTaskResponse{}, errors.Wrap(err, "initializing task")
```

2023-04-20 22:22 UTC, colinking commented on pkg/server/apidev/init.go
> +	if !req.DryRun && resp.NewTaskDefinition != nil {
Is `NewTaskDefinition` not set during dry run? Any reason not? Seems nice if dry run returns the task.

2023-04-20 22:22 UTC, colinking commented on pkg/server/apidev/init.go
> +		// Wait a maximum of five seconds for the task to be discovered.
Can you kick off rediscovery for the path? That way we don't need to wait on the file watcher to poll for changes. Specifically, call the debounced method so that it doesn't run twice when the file watcher detects the changes. See: https://github.com/airplanedev/cli/blob/06d66ddc4e611c1441c45df0c6e044ff49fd9299/pkg/server/server.go#L348-L355

2023-04-20 22:22 UTC, colinking commented on pkg/server/apidev/init.go
> +			interval := time.Millisecond * 500
Let's poll much more often, since this is all in-memory. Like every 10ms.

2023-04-20 22:22 UTC, colinking commented on pkg/server/apidev/init.go
> +	Name        string              `json:"name"`
We also need to pass the slug through. We wanted that to be editable in the modal. We can then use that as a the basis for generating a unique slug, in the off chance it isn't unique.

2023-04-21 13:42 UTC, francescaleung commented on pkg/initcmd/initcmd.go
> +	filenamesWithStatus := make([]FilenameWithStatus, len(filenames))
no strong feelings about this one, you do you :)

2023-04-21 13:49 UTC, francescaleung commented on pkg/server/apidev/init.go
> +	if !req.DryRun && resp.NewTaskDefinition != nil {
In a dry run we don't actually create any files, so a dry run SQL initialization fails when we go to convert the def into a task, even with IgnoreInvalid=true (it tries to read the entrypoint file so it can put the query into KindOptions). That's fixable, but seemed like a lot to do here. Also, we don't even need to really return the whole task; returning just the slug here would be sufficient, & would have the bonus effect of matching what we do for views (because view initialization is a lot dumber & we don't even have a view def there). Thoughts?

2023-04-21 13:52 UTC, francescaleung commented on pkg/server/apidev/init.go
> +		// Wait a maximum of five seconds for the task to be discovered.
It's still async, we'd still want to wait. Reason: if you return right away & it hasn't been picked up yet by discovery, we redirect the user to a page that 404s.

2023-04-21 13:55 UTC, francescaleung commented on pkg/server/apidev/init.go
> +	Name        string              `json:"name"`
we'll get there, I'm considering that out of scope for this particular PR

2023-04-21 15:35 UTC, colinking approved these changes

2023-04-21 15:35 UTC, colinking commented on pkg/server/apidev/init.go
> +		dfn, ok := s.Debouncers.Get(path)
The path would never be in `Debouncers` since it's a new path (unless the watcher happened to already pick it up). Add logic to initialize the debouncer if it doesn't exist (maybe just add a state function so that both codepaths can share the logic?).

2023-04-24 19:33 UTC, francescaleung commented
rerequesting for NodeFlavor + task/view discovery logic moving into state

2023-04-25 18:14 UTC, merged