Fix cached builds not discovering entities
airplanedev/cli pull request #1089
Opened 2023-04-24 15:26 UTC by ameyakhare

## Description
Introduce a build arg BUILD_ID into the bundle build dockerfile. We'll set this buildarg to the build id so that all the steps that occur underneath the ARG command cannot be cached, since the build id would be unique: https://stackoverflow.com/questions/35134713/disable-cache-for-specific-run-commands

The next step will be adding this build arg in the bundler (airport) when it executes the build.

## Test plan
Builds still work properly.

2023-04-26 15:22 UTC, leeweisberger requested changes

2023-04-26 15:22 UTC, leeweisberger commented on pkg/build/views/view.go
> +		RUN echo "$BUILD_ID"
This is going to kill the build cache which is below this line... but I guess we have to do that to discover the view every time...

2023-04-26 15:22 UTC, leeweisberger commented on pkg/build/views/view.go
> +		ARG BUILD_ID
This search seems to indicate that this will produce an error if the arg is not supplied...

Is this true? if so this should be step 2.
![image](https://user-images.githubusercontent.com/6363419/234623464-64649bc7-ab87-4f5e-87ef-72b09c2ab506.png)

2023-04-28 14:08 UTC, ameyakhare commented on pkg/build/views/view.go
> +		RUN echo "$BUILD_ID"
yeah we kinda have to do this...

2023-04-28 14:11 UTC, ameyakhare commented on pkg/build/views/view.go
> +		ARG BUILD_ID
take a look at the link. all the blocks before the arg statement are not cached, since the intermediate layer is cached. we'll have to be careful when we bump this in airport, but it is a one time check to pass in the deployment id in the build args in the builder/bundler.

2023-05-01 20:57 UTC, leeweisberger approved these changes
Let's pass the arg in from airport first before we merge this

2023-05-02 13:54 UTC, merged