Add default run permissions to task def
airplanedev/cli pull request #1100
Opened 2023-04-27 14:35 UTC by leeweisberger

## Description

Add default run permissions to task definition.

Add default run permissions to json schema.

Parse default run permissions from inline tasks (todo to add to sdk)

Add default run permissions when initializing a task

## Test plan
Added unit tests for each of the steps. have not yet tested e2e

2023-04-27 17:52 UTC, rose-huang requested changes

2023-04-27 17:52 UTC, rose-huang commented on pkg/deploy/taskdir/definitions/yaml_templates.go
> +# Manage who can view new runs of this task. Default: "task-viewers".
do we add everything to this template? just wondering since schedules / permissions / restrict. task callers arent here

2023-04-27 17:52 UTC, rose-huang commented on pkg/deploy/discover/parser/python/parser.py
> +<< << << < HEAD
can you fix this merge conflict

2023-04-27 17:52 UTC, rose-huang commented on pkg/runtime/python/python.go
> +    {{- end}}
what is this doing?

2023-04-27 17:56 UTC, leeweisberger commented on pkg/deploy/discover/parser/python/parser.py
> +<< << << < HEAD
woah

2023-04-27 18:03 UTC, leeweisberger commented on pkg/deploy/taskdir/definitions/yaml_templates.go
> +# Manage who can view new runs of this task. Default: "task-viewers".
Historically we've added everything, but I think we forgot some things. This field is pretty advanced... I'm going to go ahead and delete it. i also started a thread in slack

2023-04-27 18:05 UTC, leeweisberger commented on pkg/runtime/javascript/javascript.go
> +  const data = [
Calling out that this is a real change. It replaces tabs with spaces which is standard for js. Without this, our js tasks are ill formatted.

2023-04-27 18:06 UTC, leeweisberger commented on pkg/runtime/python/python.go
> +    {{- end}}
This is a bad diff. I added the end after the if. The diff is showing the one before

2023-04-27 21:39 UTC, rose-huang approved these changes

2023-05-02 21:04 UTC, colinking approved these changes
Sheesh, you weren't kidding! So many places to update.

2023-05-02 21:04 UTC, colinking commented on pkg/runtime/javascript/javascript.go
> +    {{- end}}
If it wasn't for the generated comments, we could get rid of this `Generate` logic and replace it with the new updaters. Though we could probably get comment generation working to make that happen... 🤔

2023-05-02 21:04 UTC, colinking commented on pkg/runtime/javascript/javascript_test.go
> +func TestGenerateInline(t *testing.T) {
🔥

2023-05-03 16:11 UTC, leeweisberger commented on pkg/runtime/javascript/javascript.go
> +    {{- end}}
We could also just add the comments to the jsdoc and be good with that

2023-05-03 16:31 UTC, merged