Support permissions as code
airplanedev/cli pull request #1134
Opened 2023-05-09 17:46 UTC by leeweisberger

## Description

Support permissions as code in the studio editor

## Test plan
See loom https://www.loom.com/share/e533afd9cc654bef860fc30df23cc67d

2023-05-09 17:50 UTC, leeweisberger commented on pkg/definitions/task_def_update.go
> +	if d.Permissions == nil && req.PermissionsSource != nil && *req.PermissionsSource == api.PermissionsSourceCode {
Here's the other place we're using the permissions source. If the permissions source is set to code, that means, for the task definition, set the permissions but don't set anything else

2023-05-09 17:50 UTC, leeweisberger commented on pkg/deploy/discover/discover_test.go
> +						Permissions: &definitions.PermissionsDefinition{
Test is unrelated to the rest of the changes, just added to add a test

2023-05-09 17:51 UTC, leeweisberger commented on pkg/server/tasks/tasks.go
> -	}
It doesn't seem like deleting this thing does anything?? We could add a feature flag, but I couldn't tell what this would do. idk if you have any other ideas @colinking

2023-05-09 17:51 UTC, leeweisberger commented on pkg/initcmd/task.go
> +		if req.Flagger == nil || !req.Flagger.Bool(ctx, req.Logger, flagsiface.PermissionsAsCode) {
This feature flag is needed to ensure that when initializing a task, we don't set the permissions

2023-05-09 17:52 UTC, leeweisberger commented on pkg/definitions/updaters/javascript_test.go
> +			name: "empty_explicit_permissions",
This test should also be unrelated to the changes here... just thought it was a good test

2023-05-10 13:49 UTC, colinking requested changes
Requesting changes to discuss the email/slug <> ID issue.

2023-05-10 13:49 UTC, colinking commented on pkg/api/client.go
> +	}
If `*PermissionsSource != "code"`, should `req.Permissions` be `nil`?

2023-05-10 13:49 UTC, colinking commented on pkg/definitions/task_def.go
> +		RequireExplicitPermissions: d.Permissions != nil && d.Permissions.RequireExplicitPermissions,
Is it not valid to set `requireExplicitPermissions: true` and not set `permissions`? Users with admin permissions would still have access.

2023-05-10 13:49 UTC, colinking commented on pkg/definitions/task_def.go
> +		if d.Permissions.RequireExplicitPermissions {
Nit, I'd switch this `if` case. Seems easier to read.
```suggestion
		if !d.Permissions.RequireExplicitPermissions {
		// If we don't require explicit permissions but permissions have been set. This means that
		// ...
```

2023-05-10 13:49 UTC, colinking commented on pkg/definitions/task_def.go
> +			task.PermissionsSource = (*api.PermissionsSource)(pointers.String(string(api.PermissionsSourceCode)))
Shouldn't `PermissionsSource` also get set to "code" whenever `RequireExplicitPermissions == true`?

2023-05-10 13:49 UTC, colinking commented on pkg/definitions/task_def_test.go
> +				DefaultRunPermissions:      (*api.DefaultRunPermissions)(pointers.String(string(api.DefaultRunPermissionTaskViewers))),
Nit: could we make a generic version of `pointers` that works for these enums? e.g. https://go.dev/play/p/Xsy1HmZb490

2023-05-10 13:49 UTC, colinking commented on pkg/definitions/task_def.go
> +					SubUserID: &p,
Aren't we providing email addresses and group slugs? Not IDs?

Assuming we add logic for resolving emails/group slugs, don't add the API logic into the `definitions` package. Take a look at what we do for resources, where we have to resolve IDs to slugs and vice versa. Let the callsite decide how to do the lookups, as this behavior will vary between e.g. the builder and the studio.

2023-05-10 13:49 UTC, colinking commented on pkg/print/types.go
> +	PermissionsSource          *libapi.PermissionsSource    `json:"permissionsSource" yaml:"-"`
This struct is used for printing out tasks, e.g. if you do `airplane tasks get`. You can change how the task is printed, either JSON or YAML. All fields should have both json and yaml struct tags set. Can you add them to all three permission fields here and confirm that these fields are printed correctly via `airplane tasks get`?

2023-05-10 13:49 UTC, colinking commented on pkg/server/tasks/tasks.go
> -	}
The web client does some sanitization which IIRC sets `permissions: {}`. So this is fine.

2023-05-10 13:50 UTC, colinking commented on pkg/definitions/updaters/javascript_test.go
> +			name: "empty_explicit_permissions",
Can you also add tests where real permissions are set? Same with the Python and YAML updaters.

2023-05-10 15:07 UTC, leeweisberger commented on pkg/definitions/updaters/javascript_test.go
> +			name: "empty_explicit_permissions",
This is already tested in the "all" test

2023-05-10 15:21 UTC, leeweisberger commented on pkg/definitions/task_def.go
> +		RequireExplicitPermissions: d.Permissions != nil && d.Permissions.RequireExplicitPermissions,
It is valid.

`d.Permissions` is a pointer so we have to check if it's null before we check for requireExplicitPermissions. For the case you outlined, d.Permissions will be non-nil, d.Permissions.RequireExplicitPermissions will be true, and d.Permissions will contain no additional permissions.

Does this make sense?

2023-05-10 19:11 UTC, leeweisberger commented on pkg/definitions/task_def.go
> +					SubUserID: &p,
Yeah man there's a lot to do! Missed this in testing because I validated that the field was set, but it wasn't set correctly. Updated and manualyl tested this (plus added unit tests for the conversion)

2023-05-10 19:30 UTC, leeweisberger commented
GH actions is having issues, but I made changes, wrote unit tests and manually tested

2023-05-10 20:33 UTC, colinking approved these changes

2023-05-10 20:33 UTC, colinking commented on pkg/cli/initcmd/task.go
> +			Groups:             groupsResp.Groups,
These are only necessary if the task has explicit permissions set, correct? Maybe this should be a function instead so that we only do the HTTP requests if necessary?

```go
definitions.NewDefinitionOptions{
// ...
LookupUsersGroups: func() ([]Users, []Groups, error) {
		usersResp, err := client.ListTeamUsers(ctx, client.TeamID())
		if err != nil {
			return nil, nil, err
		}
		var users []libapi.User
		for _, user := range usersResp.Users {
			users = append(users, user.User)
		}

		groupsResp, err := client.ListGroups(ctx)
		if err != nil {
			return nil, nil, err
		}
		return users, groupsResp.Groups, nil
}
}
```

2023-05-10 20:33 UTC, colinking commented on pkg/definitions/task_def.go
> +func (d Definition) addPermissionsToTask(task *api.Task, opts GetTaskOpts) error {
Nice

2023-05-10 20:33 UTC, colinking commented on pkg/cli/initcmd/task.go
> +			Groups:             groupsResp.Groups,
FWIW, in retrospect I would have done the same for AvailableResources.

2023-05-11 14:40 UTC, leeweisberger commented on pkg/cli/initcmd/task.go
> +			Groups:             groupsResp.Groups,
I did this for all of them, both in the init flow and the update flow.

If there are no explicit permissions, don't fetch users and groups
If there are no resources, don't fetch resources

2023-05-11 17:23 UTC, merged