Add python runtime
airplanedev/cli pull request #170
Opened 2021-06-10 08:04 UTC by yields

Initial implementation of Python runtime, it's inspired by the simplicity
of the node.js shim.

Note that the shim is python3.5+ because of module loading, i don't think
it's a big issue because it matches our image version. We can iterate on
this later and add python 2 support if needed.

2021-06-10 18:30 UTC, joshma commented on pkg/build/shim.py
> +		raise Exception("shim: executing {{.Entrypoint}} - {}".format(e))
You use `raise from` https://stackoverflow.com/questions/9157210/how-do-i-raise-the-same-exception-with-a-custom-message-in-python/29442282#29442282

```suggestion
		raise Exception("shim: executing {{.Entrypoint}}") from e
```

2021-06-10 18:32 UTC, joshma commented on pkg/build/shim.py
> +	if len(args) != 3:
Oops nevermind, ignore me 😅

2021-06-10 19:20 UTC, colinking requested changes
Looking good! Some merge-related comments

2021-06-10 19:20 UTC, colinking commented on pkg/build/python.go
> +		Shim:            strings.Join(strings.Split(shim, "\n"), "\\n\\\n"),
wdyt of pulling this `\n\` formatting out into a function shared with JS?

2021-06-10 19:20 UTC, colinking commented on pkg/build/shim.py
> +
Could we drop up this leading line?

2021-06-10 19:20 UTC, colinking commented on pkg/build/shim.py
> +
Could we add a comment here? Similar to JS: https://github.com/airplanedev/cli/blob/6336f8ab85b43b42bde1a6d9518477b474f4b6fd/pkg/build/node.go#L73

```
# This file includes a shim that will execute your task code.
```

2021-06-10 19:20 UTC, colinking commented on pkg/build/shim.py
> +	spec.loader.exec_module(mod)
fancy

2021-06-10 19:20 UTC, colinking commented on pkg/cmd/tasks/deploy/script.go
> +		}
wdyt of passing `Workdir` through in the `Request` struct instead? Think it's fine that only Node would look at it for now.

2021-06-10 19:20 UTC, colinking commented on pkg/cmd/tasks/deploy/script.go
> +	}
How would you feel about `panic`-ing here in a `default` case?

2021-06-10 19:20 UTC, colinking commented on pkg/runtime/python/python.go
> +var code = template.Must(template.New("py").Parse(`# {{.Comment}}
^ noting that you'll need to add a `FormatComment` implementation from: https://github.com/airplanedev/cli/pull/172/files#diff-03794acab66295250e50c8ecc7a7d6371142b27407bce017384597dbe8341276R91

And remove the `#` here

2021-06-10 19:20 UTC, colinking commented on pkg/cmd/tasks/execute/execute.go
> +		if _, ok := runtime.Lookup(file); ok {
🔥

2021-06-10 19:20 UTC, colinking commented on pkg/cmd/tasks/execute/execute.go
> +	}
^ looks like a bad merge

2021-06-11 10:26 UTC, yields commented on pkg/cmd/tasks/execute/execute.go
> +	}
hmm that was intentional, I removed the previous code snippet because it would fetch the task twice if it's a file...

2021-06-11 10:28 UTC, yields commented on pkg/cmd/tasks/deploy/script.go
> +		}
hmm, what's the benefit of doing so?

2021-06-11 13:55 UTC, colinking commented on pkg/cmd/tasks/execute/execute.go
> +	}
Yeah, but that handles the case where you have a file with the same name as the slug. Which is common enough in the case where you place your task in a directory with the same name as the slug and then try and execute that task from the parent directory.

For example:

```
outputs/
  main.js
```

```
airplane execute ./outputs/main.js
// vs
airplane execute outputs
```

Maybe a better fix would be for us to conditionally treat it as a slug/file if it references a _file_ (not a directory)?

2021-06-11 16:00 UTC, yields commented on pkg/cmd/tasks/execute/execute.go
> +	}
AFAIK, `airplane execute outputs` would treat it as a slug and error? if not that should be a bug hmm

2021-06-14 14:35 UTC, colinking commented on pkg/cmd/tasks/execute/execute.go
> +	}
The current behavior would see the outputs directory and try to deploy from script, even though we want to instead deploy the task with `slug=outputs`. If we can notice it is a directory and then skip straight to trying it as a slug then that should help.

2021-06-14 14:49 UTC, colinking approved these changes

2021-06-14 14:49 UTC, colinking commented on pkg/build/python.go
> +func python(root string, args api.KindOptions) (string, error) {
FYI moved these functions to use `api.KindOptions`, so I had renamed `args -> options`

2021-06-14 14:49 UTC, colinking commented on pkg/runtime/runtime.go
> +	// an `ErrNotImplemented`.
lmao.... Thanks for fixing this comment!

2021-06-14 15:15 UTC, merged