Improve layer caching
airplanedev/cli pull request #195
Opened 2021-06-21 10:25 UTC by yields

When a docker layer changes docker will invalidate all subsequent layers. This means that if we do the following:

		ADD . /src
		RUN npm install /src/package.json

It means that every time a user changes their source code we will re-install the package.json, instead we should do the following:

		ADD package.json /src
		RUN npm install /src/package.json
		ADD . /src

2021-06-21 16:34 UTC, yields commented
Removed the node changes to keep this working with workspaces. For node we may detect workspaces and then use that layer caching improvement. I'll put it in another PR.

2021-06-21 16:46 UTC, joshma requested changes

2021-06-21 16:46 UTC, joshma commented on pkg/build/node.go
> +		ADD package.json ./airplane
BTW - can we use COPY instead of ADD? ADD does too much; IMO we should use COPY by default.

2021-06-21 16:46 UTC, joshma commented on pkg/build/node.go
> +		ADD . /airplane
This should be moved back to earlier (L98), since `.` is needed for `npm install`!

2021-06-21 16:46 UTC, joshma commented on pkg/build/python.go
> +		ADD requirements.txt .
might as well fix the indentation here / L40? this is getting weird 😂

2021-06-21 16:46 UTC, joshma commented on pkg/build/python.go
> +    ADD . .
(same comment, ADD -> COPY)

2021-06-21 16:46 UTC, joshma commented on pkg/build/versions.json
> +      "tag": "3.9.4-alpine3.13",
will `alpine` work for node/python? my understanding is that there tends to be os dependencies in both languages, so it might not always be portable to e.g. alpine (which is why we went with debian at first)

2021-06-21 16:46 UTC, joshma commented on pkg/build/python.go
> +    RUN touch __init__.py
didn't see this the first time around, but is this actually needed here? it defines the directory it's in as a package, but...the working directory is not usually a package

2021-06-21 16:56 UTC, yields commented on pkg/build/node.go
> +		ADD . /airplane
what's with the `!` 😂? is this because there's maybe a `lock` file for yarn or npm?

2021-06-21 16:58 UTC, yields commented on pkg/build/python.go
> +    RUN touch __init__.py
there's an error while importing from the shim if we don't add it :/

2021-06-21 17:01 UTC, joshma commented on pkg/build/node.go
> +		ADD . /airplane
Oh, the exclamation just because this is a tricky thing that I wanted to emphasize! :)

This is what I was mentioning earlier, regarding NPM workspaces. You cannot always assume that `package.json+package-lock.json+yarn.lock` are the only files necessary for `npm install / yarn install`. If you're installing in `/airplane/server` you might have code in `/airplane` and `/airplane/shared` that is needed for install, and so you have to make sure you add that earlier.

2021-06-21 17:09 UTC, joshma commented on pkg/build/python.go
> +    RUN touch __init__.py
hm, can you repro / share the error? I'm like 70% sure that either this won't error or, if it does error, there's a more proper solution 😇

2021-06-22 14:23 UTC, yields commented on pkg/build/python.go
> +    RUN touch __init__.py
you're right, it seems that it didn't work in the previous method we used to import modules in the shim. Removed `__init__.py`.

2021-06-22 14:24 UTC, yields commented on pkg/build/versions.json
> +      "tag": "3.9.4-alpine3.13",
It depends what do you mean by work? of-course it will, Ibinaries/sharedlibs that are included in debian won't work here tho. but it's totally worth it imho, works for the simple case, other cases could use the `.yml` files or ship their own images.

2021-06-22 17:44 UTC, joshma commented on pkg/build/versions.json
> +      "tag": "3.9.4-alpine3.13",
Well alpine uses musl libc instead of glibc (https://hub.docker.com/_/node has a warning about this), and so I'm concerned that basic packages might not even install properly. The default node image uses debian. So by "work" I mean "work in ~90% of use cases". 

I gave it a quick try and it seems like numpy won't work on alpine, but e.g. openssl / node-gyp works on alpine.So it's not super clear what breaks.

> other cases could use the .yml files or ship their own images

By "use .yml files" do you mean use the dockerfile builder instead? I suppose we could eventually allow configuring the base OS if necessary, for `node`?

2021-06-22 17:45 UTC, joshma approved these changes

2021-06-24 14:33 UTC, yields commented on pkg/build/versions.json
> +      "tag": "3.9.4-alpine3.13",
yeah that too, we can come up with a lot of ways to do it. but I think it's worth it and will work. I've been using alpine for Go consistently and musl libc works well.

2021-06-24 14:35 UTC, merged

2021-06-24 16:40 UTC, joshma commented on pkg/build/versions.json
> +      "tag": "3.9.4-alpine3.13",
Yeah ok we can see where this goes. :)

I get it that Go works, my main warning is that it's a lot hairier outside of Go. Node and Python packages have a history of depending on C libraries (e.g. node-gyp https://github.com/mhart/alpine-node/issues/27 https://github.com/nodejs/node-gyp/issues/1855).