Batch deploy a list of files or a directory
airplanedev/cli pull request #312
Opened 2021-11-15 23:10 UTC by leeweisberger

Support deploying multiple files/directories. The code recursively searches through all provided files/directories and deploys all airplane tasks in them concurrently.

The code waits for all of the tasks to finish and then prints a summary of all successes/errors. If at least one task errors, the entire script errors.

Logs for each task are interwoven

---

Screenshot of what it looks like with two tasks being deployed simultaneously
![image](https://user-images.githubusercontent.com/6363419/141867081-a059a8ee-9a44-448b-aba5-1faba4c7c7a8.png)

2021-11-15 23:10 UTC, leeweisberger commented on pkg/build/remote.go
> +func (d *Deployer) getRegistryToken(ctx context.Context, client *api.Client) (registryToken api.RegistryTokenResponse, err error) {
This ensures that we only authenticate once.

2021-11-17 05:49 UTC, joshma requested changes

2021-11-17 05:49 UTC, joshma commented on pkg/build/remote.go
> +	buildLog(api.LogLevelInfo, loader, req.Def.Slug, logger.Gray("Building with %s as root...", relpath(req.Root)))
heh minor but I think this could be a valid place to place `slug` onto the `ctx`? 😇 up to you but would make this cleaner

2021-11-17 05:49 UTC, joshma commented on pkg/cmd/tasks/deploy/deploy.go
> +		Args: cobra.MinimumNArgs(1),
By doing this, this removes the `-f` flag support (in which case it would have N=0 args). Is that intentional?

2021-11-17 05:49 UTC, joshma commented on pkg/cmd/tasks/deploy/deploy.go
> +				cfg.filesOrDirectories = args
what's `cfg.file` here for? in the case of `N=1`?

2021-11-17 05:49 UTC, joshma commented on pkg/cmd/tasks/deploy/script.go
> +		)
while you're here, can we deemphasize the CLI cmd? I want to stop suggesting `exec` locally.

```
some_task_slug:
    Deploy status: succeeded
    Visit the task: https://...
```

(I was considering adding more fields, but maybe that should go at the start? Will do a sep. comment)

2021-11-17 05:49 UTC, joshma commented on pkg/cmd/tasks/deploy/script.go
> +func (d *scriptDeployer) deployFromScriptHelper(ctx context.Context, cfg config, g *errgroup.Group) (rErr error) {
for each of the scripts we deploy, can print some summary at the beginning? I've wished we had this, something to allow a user to sanity check:
- task slug (maybe also URL)
- task type / runtime (python 3.7, node 14.x, etc.)
- root directory (and working directory if different) - helps users realize if e.g. we picked up a requirements.txt from a parent directory

dunno which of these are easy to include, but would be nice to print these out before the deploy starts

2021-11-17 05:49 UTC, joshma commented on pkg/cmd/tasks/deploy/script.go
> +var ignoredDirectories = map[string]bool{
we have airplane ignore - https://docs.airplane.dev/platform/airplane-ignore - maybe we should just honor that?

2021-11-17 05:49 UTC, joshma commented on pkg/cmd/tasks/deploy/script.go
> +		} else {
minor but can this use an early return instead?

2021-11-17 05:49 UTC, joshma commented on pkg/cmd/tasks/deploy/script.go
> +			return d.deployFromScriptHelper(ctx, configCopy, g)
this recursion is a bit funny...you're doing a search while kicking off builds. I think this can be separated more cleanly. `deployFromScriptHelper` could be renamed to `discoverScripts` and recursively search to return a slice of files, and then in `deployFromScript` you could take that slice and `g.Go()` each item.

2021-11-17 22:31 UTC, leeweisberger commented on pkg/cmd/tasks/deploy/deploy.go
> +		Args: cobra.MinimumNArgs(1),
Yeah I've removed it. Seems like it was deprecated and I didn't want to change code to support it if it is deprecated. Let me know if I should keep it around

2021-11-17 22:32 UTC, leeweisberger commented on pkg/cmd/tasks/deploy/deploy.go
> +				cfg.filesOrDirectories = args
Removed

2021-11-17 22:34 UTC, leeweisberger commented on pkg/cmd/tasks/deploy/script.go
> +		)
Updated - this is what it looks like now: 
![image](https://user-images.githubusercontent.com/6363419/142293347-307408e2-972f-4ea1-ab68-5358e491e258.png)

2021-11-17 22:35 UTC, leeweisberger commented on pkg/cmd/tasks/deploy/script.go
> +func (d *scriptDeployer) deployFromScriptHelper(ctx context.Context, cfg config, g *errgroup.Group) (rErr error) {
This is what it looks like now
![image](https://user-images.githubusercontent.com/6363419/142293443-f348ff1c-18f9-498e-b31a-2beacd8c36d4.png)

Didn't do runtime b/c that's a bit harder to get

2021-11-17 22:38 UTC, leeweisberger commented on pkg/cmd/tasks/deploy/script.go
> +var ignoredDirectories = map[string]bool{
Tried doing this but reverted:
1. It's kind of hard because we don't have the information needed for our ignore call at the time we want to use it (requires reading the file, fetching type, getting root).
2. I don't think it's exactly the same concept - ignore are files that we don't want to push even if they are in a root directory. This is places where we will not discover airplane tasks.

This code isn't even necessary - it just avoids searching through folders we know won't have airplane tasks. Could see us adding configuration later where we allow deploying all tasks in a directory except tasks of a slug or in a sub directory

2021-11-17 22:38 UTC, leeweisberger commented on pkg/cmd/tasks/deploy/script.go
> +			return d.deployFromScriptHelper(ctx, configCopy, g)
Yup good idea. Changed to this pattern

2021-11-17 22:39 UTC, leeweisberger commented on pkg/cmd/tasks/deploy/deploy.go
> +	ext := filepath.Ext(cfg.filesOrDirectories[0])
We now only support yml for single files. Not a regression but I didn't want to implement the same discovery stuff for a deprecated path

2021-11-17 22:40 UTC, leeweisberger commented on pkg/cmd/tasks/deploy/script.go
> +func getTaskConfigFromScript(ctx context.Context, client api.Client, script script) (getTaskConfigFromScriptResp, error) {
I don't love this, but we need this info when printing the summary at the start and when running the build. And I don't want to run through this twice

2021-11-17 22:41 UTC, leeweisberger commented on pkg/cmd/tasks/deploy/script.go
> -	r, err := runtime.Lookup(cfg.file, task.Kind)
moved all of this to a helper below

2021-11-17 22:43 UTC, joshma commented on pkg/cmd/tasks/deploy/deploy.go
> +		Args: cobra.MinimumNArgs(1),
Hrm I think it's probably fine to remove cc @colinking

2021-11-17 22:44 UTC, leeweisberger commented on pkg/cmd/tasks/deploy/script.go
> +func relpath(root string) string {
moved this from another file

2021-11-18 17:51 UTC, joshma approved these changes

2021-11-18 17:51 UTC, joshma commented on pkg/cmd/tasks/deploy/script.go
> +		code, err := ioutil.ReadFile(fileOrDirectory)
AD - I think we can do this in a separate PR, but I'm concerned about perf + reading too much data. I think we can do (1) have a list of extensions we'll actually open, and (2) only read the first 4096 bytes or something to determine the slug.

2021-11-18 17:51 UTC, joshma commented on pkg/cmd/tasks/deploy/deploy.go
> +	filesOrDirectories []string
Can we rename this to `paths`?

2021-11-18 17:51 UTC, joshma commented on pkg/cmd/tasks/deploy/script.go
> +var ignoredDirectories = map[string]bool{
update: AD, add `.git` and double check what happens. it should at least error, I suppose.

2021-11-18 17:51 UTC, joshma commented on pkg/cmd/tasks/deploy/script.go
> +	var pluralize string
minor but I sort of like doing `noun := "task"` and then setting `noun = "tasks"` if it's plural?

2021-11-18 17:51 UTC, joshma commented on pkg/cmd/tasks/deploy/script.go
> +type getTaskConfigFromScriptResp struct {
not super important to name this since its a private struct, but...maybe `type taskConfig`? or `type taskSummary`?

2021-11-18 18:00 UTC, leeweisberger commented on pkg/build/remote.go
> +func uploadArchive(ctx context.Context, client *api.Client, taskSlug, archivePath string, loader *logger.Loader) (string, error) {
yeah it was never used. Also removed taskSlug

2021-11-18 18:57 UTC, merged