Update node dockerfile to be more cachable
airplanedev/cli pull request #316
Opened 2021-11-16 16:29 UTC by leeweisberger

Convert Dockerfile to use [nodejs best practices](https://nodejs.org/en/docs/guides/nodejs-docker-webapp/#creating-a-dockerfile)

In practice, we are currently reinstalling all dependencies whenever code changes. After this pr, we will use cached dependencies unless the dependencies themselves change.

2021-11-16 16:57 UTC, colinking commented on pkg/build/node.go
> +		COPY package*.json /airplane/
IIRC, we did it that way as a temporary solution to support npm/yarn workspaces. We have some WIP tests for workspaces, which would be great to get running: https://github.com/airplanedev/cli/blob/a1ff65cfdd2767a44cabaa80d3fa67ff6a179e39/pkg/build/node_test.go#L114-L124

You might be able to get away with detecting if a task uses yarn/npm workspaces and falling back on the previous behavior.

2021-11-16 21:06 UTC, joshma requested changes

2021-11-16 21:06 UTC, joshma commented on pkg/build/node.go
> +		COPY package*.json /airplane/
Yepp @colinking  is right. If you are in /src/foo/main, `yarn install` with workspaces looks at /src/foo/main/package.json but also /src/foo/package.json (we allow this via distinct root vs working dir). This in turn might reference other silbling packages, so you might need /src/foo/somedep/* as a result.

Maybe we can just check if root and working dir are the same. If they are the same, then I think it's safe to cache this way.

Note that longer term, I think the _right_ behavior is to skip Docker caching and explicitly save/restore NPM packages from cache.

2021-11-17 17:08 UTC, leeweisberger commented on pkg/build/node.go
> +		COPY package*.json /airplane/
Ok good callouts - didn't even know yarn workspaces was a thing ;)

I updated to handle yarn workspaces (we only do the optimization if we're not using workspaces). I also enabled the test - had to make a small change to get it to pass, but it's better than no test - the test failed on my previous change and passes now

2021-11-17 18:35 UTC, colinking approved these changes

2021-11-17 18:35 UTC, colinking commented on pkg/examples/typescript/yarnworkspaces/pkg2/src/index.ts
> +import {name as pkg1name} from 'pkg1/src'
:awyis:

2021-11-17 18:35 UTC, colinking commented on pkg/build/node.go
> +		{{if not .UsesYarnWorkspaces}}
There are also npm workspaces: https://docs.npmjs.com/cli/v7/using-npm/workspaces

Could you add support for detecting those too? And add a test? 🙏🏻

2021-11-17 19:40 UTC, leeweisberger commented on pkg/build/node.go
> +		{{if not .UsesYarnWorkspaces}}
yes! the code as is will work for both and I'll add a test to confirm

2021-11-17 20:03 UTC, joshma approved these changes
approving but removed `merge` label since the tests were commented out?

2021-11-17 20:03 UTC, joshma commented on pkg/build/node_test.go
>  	tests := []Test{
what happened to these tests?

2021-11-17 20:10 UTC, merged