Handle deploying from a task definition file
airplanedev/cli pull request #340
Opened 2021-12-06 21:06 UTC by francescaleung

I punted on handling explicit permissions and new tasks, will address in later PRs. There's some thought towards handling multiple task definition files, but it's not fully fleshed out. This patch works for both local + remote builds.

I don't know how well this works for complicated Root determination, & what exactly should happen if the task defn file is not in the working directory & the entrypoint is not in the same directory as the task defn file. I suspect this doesn't handle that well & I'm not sure I understand the concept of the Root well enough to figure out exactly what should happen here. This works for the case where the working directory is where the task defn file + entrypoint are. Filed a ticket for examining Root complications in more detail.

Resolves AIR-2462, AIR-2546.

2021-12-06 22:58 UTC, leeweisberger requested changes
One main comment - we really want this to flow:
- Walk through filesystem and discover tasks (we can discover script tasks, yaml tasks, defnv3 tasks).
- Transform the task to a single abstraction (task config) from the given task type
- Once we have N task configs, deploy them using a single codebase.

This is basically the visitor pattern (https://refactoring.guru/design-patterns/visitor) where each type of task config has the ability to recognize a task and convert it to a task config

2021-12-06 22:58 UTC, leeweisberger commented on pkg/build/remote.go
> +	if req.Def_0_3 != nil {
We're going to delete the whole def v2 path right? So all of these if/elses are going to go away?

2021-12-06 22:58 UTC, leeweisberger commented on pkg/build/remote.go
> +	if req.Def_0_3 != nil {
Might want to use `def` for the new version and then `def_deprecated` or `dev_0_2` for the old? That way when we clean this up, we just delete all of the things dealing with the deprecated def and we don't have to rename anything. Up to you

2021-12-06 22:58 UTC, leeweisberger commented on pkg/taskdir/directory.go
> +func Open(file string, use_0_3 ...bool) (TaskDirectory, error) {
What's up with the multiple bools? What's going on here?

2021-12-06 22:58 UTC, leeweisberger commented on pkg/taskdir/definitions/definitions.go
> +	def.Arguments = upgradeArguments(def.Arguments)
what's the point of this refactor?

2021-12-06 22:58 UTC, leeweisberger commented on pkg/taskdir/definitions/def_0_3.go
> +	// Convert parameters.
Just for readability, can you break this into a helper function

2021-12-06 22:58 UTC, leeweisberger commented on pkg/taskdir/definitions/def_0_3.go
> +	if d.SQL != nil || d.REST != nil {
break this into a constant map - types that have resources

2021-12-06 22:58 UTC, leeweisberger commented on pkg/taskdir/definitions/def_0_3.go
> +	// Convert kind-specific things.
No way around this switch statement? In the old code it looks like we used mapstructure.Decode to do this automatically. 

How many steps do you have to take to add a new field to a python task e.g.? If it obvious where you have to add these things? Where are we going to mess up in the future? How about adding a new task type?

2021-12-06 22:58 UTC, leeweisberger commented on pkg/cmd/tasks/deploy/defn.go
> +func deployFromTaskDefn(ctx context.Context, cfg config) error {
We still need to do some sort of discovery step to discover all task def tasks in a package.

2021-12-06 22:58 UTC, leeweisberger commented on pkg/cmd/tasks/deploy/defn.go
> +		logger.Log("\n" + logger.Bold(tc.def_0_3.Slug))
All these logs should really be in one place. 

We might want to change around some architecture here.

This is how I think it should go:
Rather than having N ways to deploy a task, we should have N ways to discover a task. We have one master discover function that goes through all files and discovers defn tasks, yaml tasks, and script tasks. Then when a task is discovered, it is transformed into a single abstraction (task config). Then we have one code path that deploys a task config.

2021-12-07 21:44 UTC, francescaleung commented on pkg/build/remote.go
> +	if req.Def_0_3 != nil {
Yes--we should be upgrading Definition_0_2 structs to Definition_0_3 structs. There's a ticket filed for this.

2021-12-07 21:55 UTC, francescaleung commented on pkg/taskdir/definitions/def_0_3.go
> +	if d.SQL != nil || d.REST != nil {
Optionally: maybe this is a `lib/build` or `runtime` concern, does this type need resources? what resources does this type need?

2021-12-07 21:56 UTC, francescaleung commented on pkg/taskdir/directory.go
> +func Open(file string, use_0_3 ...bool) (TaskDirectory, error) {
default false. I'll just change it to explicit true/false, no defaults.

2021-12-07 21:59 UTC, francescaleung commented on pkg/taskdir/definitions/definitions.go
> +	def.Arguments = upgradeArguments(def.Arguments)
Definition_0_3 (which is _not_ aliased to Definition) also has an UpgradeJST method.

2021-12-07 22:14 UTC, francescaleung commented on pkg/taskdir/definitions/def_0_3.go
> +	// Convert kind-specific things.
Old code is using a structure a lot more similar to how we keep things in the database, which is why we can just use mapstructure.Decode.

The part that's missing here is taking an api.Task & deriving a Definition from it. For adding a new field to a kind-specific thing: add it in the schema.json, add it in the Definition -> UpdateTaskRequest method, add it in the (currently nonexistent) api.Task -> Definition method. Adding a new task type means all of that, plus also adding it to main Kind switch & all the other switches on kind (currently: Entrypoint, Root, UpgradeJST).

Instead of switching on Kind, we could have a TaskKind interface instead. Then for new task types, we'd need to add it to the schema.json, implement the TaskKind interface, add it to the main Kind / TaskKind switches. Does that sound better?

2021-12-07 22:14 UTC, francescaleung commented on pkg/cmd/tasks/deploy/defn.go
> +func deployFromTaskDefn(ctx context.Context, cfg config) error {
Agree--as discussed, punting on this for now.

2021-12-07 22:15 UTC, francescaleung commented on pkg/cmd/tasks/deploy/defn.go
> +		logger.Log("\n" + logger.Bold(tc.def_0_3.Slug))
Agree--as discussed, punting on this for now.

2021-12-07 22:53 UTC, francescaleung commented on pkg/build/remote.go
> +	if req.Def_0_3 != nil {
The other possibility here for cleaner user code is a DefinitionInterface that abstracts away the underlying def implementation. I think this is probably a better way to go.

2021-12-08 23:41 UTC, leeweisberger approved these changes
A few naming issues. otherwise lgtm

2021-12-08 23:41 UTC, leeweisberger commented on pkg/taskdir/definitions/def_0_3.go
> +	updateTaskRequest(context.Context, *api.Client, *api.UpdateTaskRequest) error
I don't love this name - it sounds like this is actively updating something while it's really just hydrating. Maybe `hydrateTaskRequest`?

2021-12-08 23:41 UTC, leeweisberger commented on pkg/taskdir/definitions/def_0_3.go
> +func (d Definition_0_3) UpdateTaskRequest(ctx context.Context, client *api.Client, image *string) (api.UpdateTaskRequest, error) {
This isn't updating anything right? Make this `getUpdateTaskRequest`?

2021-12-08 23:41 UTC, leeweisberger commented on pkg/taskdir/definitions/def_0_3.go
> +func (d Definition_0_3) convertParameters(ctx context.Context, client *api.Client, req *api.UpdateTaskRequest) error {
this func is strangely named to. `convert` makes me think it should return something, but it returns nothing. It's not obvious that it's updating the req. Maybe `addParamsToReq` or `hydrateReqWithParams`

2021-12-08 23:41 UTC, leeweisberger commented on pkg/taskdir/definitions/def_0_3.go
> +func (d Definition_0_3) convertPermissions(ctx context.Context, client *api.Client, req *api.UpdateTaskRequest) error {
same here. Not really converting? and below

2021-12-09 19:08 UTC, merged