Create new task in deploy by defn
airplanedev/cli pull request #344
Opened 2021-12-08 16:56 UTC by francescaleung

Resolves AIR-2463.

2021-12-08 17:25 UTC, leeweisberger approved these changes

2021-12-09 03:39 UTC, leeweisberger requested changes

2021-12-09 03:39 UTC, leeweisberger commented on pkg/cmd/tasks/deploy/defn.go
> +		if ok, err := utils.ConfirmWithAssumptions(question, cfg.assumeYes, cfg.assumeNo); err != nil {
Is this still going to prompt if there is no terminal? Like in CI? We should probably check

2021-12-09 15:18 UTC, francescaleung commented on pkg/cmd/tasks/deploy/defn.go
> +		if ok, err := utils.ConfirmWithAssumptions(question, cfg.assumeYes, cfg.assumeNo); err != nil {
yea, we can check. I'm thinking it defaults to no (don't create a new task) & logs a warning. Sound good?

2021-12-09 18:20 UTC, leeweisberger approved these changes

2021-12-09 18:20 UTC, leeweisberger commented on pkg/cmd/tasks/deploy/defn.go
> +		if ok, err := utils.ConfirmWithAssumptions(question, cfg.assumeYes, cfg.assumeNo); err != nil {
Yeah sounds good

2021-12-09 19:04 UTC, merged