Discover & bulk deploy tasks regardless of type.
airplanedev/cli pull request #345
Opened 2021-12-09 03:45 UTC by leeweisberger

When a user runs airplane deploy, recursively search all files for either script (lite) tasks or yaml tasks. Convert found airplane tasks into task configs. Batch deploy task configs.

---

There's a lot of code here - definitely some refactoring mixed in. Most of the refactoring supports the goal of condensing discover / deploy code and other is to support testing (we really have to start creating interfaces!!!).

Might be useful to review in person @francescaleung

2021-12-09 03:45 UTC, leeweisberger commented on pkg/api/client.go
> +type APIClient interface {
Allow client to be mocked in tests

2021-12-09 03:45 UTC, leeweisberger commented on pkg/build/build.go
> +type BuildCreator interface {
Interface so the remote / local build creator's (much better name than deployer!) can be mocked out

2021-12-09 03:46 UTC, leeweisberger commented on pkg/build/build.go
> -func Run(ctx context.Context, deployer *Deployer, req Request) (*build.Response, error) {
This was a dumb way of doing this. Now the caller creates a build creator (either local or remote) and just calls `CreateBuild`

2021-12-09 03:47 UTC, leeweisberger commented on pkg/build/local.go
> +	registryTokenGetter
This allows the local/remote build creators to share token getting code

2021-12-09 03:48 UTC, leeweisberger commented on pkg/cmd/tasks/deploy/defn.go
> -package deploy
this code has been moved into
* pkg/cmd/tasks/deploy/discover/defn_discover.go (discovering tasks and converting to task_configs)
* pkg/cmd/tasks/deploy/deploy_tasks.go (actually running the deploy/update)

2021-12-09 03:49 UTC, leeweisberger commented on pkg/cmd/tasks/deploy/deploy.go
> +	if !cfg.dev && (ext == ".yml" || ext == ".yaml") && len(cfg.paths) == 1 {
You can only get legacy yaml by not including the dev flag and only including one file. I think we should remove this code after we launch yaml and move our outstanding customer onto it

2021-12-09 03:50 UTC, leeweisberger commented on pkg/cmd/tasks/deploy/deploy.go
> +	d := &discover.Discoverer{
This is the entrypoint. Pretty easy to follow:
1. Discover tasks
2. Deploy discovered tasks

2021-12-09 03:51 UTC, leeweisberger commented on pkg/cmd/tasks/deploy/deploy_tasks.go
> -func (d *scriptDeployer) discoverScripts(ctx context.Context, paths ...string) ([]script, error) {
This was moved to the discovery phase!

2021-12-09 03:52 UTC, leeweisberger commented on pkg/cmd/tasks/deploy/deploy_tasks.go
> +	if ok, err := libBuild.NeedsBuilding(kind); err != nil {
I took this code from the yaml code.

We're going to need to update this to support sql / rest (currently errors)

2021-12-09 03:53 UTC, leeweisberger commented on pkg/cmd/tasks/deploy/discover/defn_discover.go
> +package discover
All of this code is copy pasted.

2021-12-09 03:54 UTC, leeweisberger commented on pkg/cmd/tasks/deploy/discover/discover.go
> +package discover
All of this code is copy pasted except where I call out below

2021-12-09 03:54 UTC, leeweisberger commented on pkg/cmd/tasks/deploy/discover/discover.go
> +			taskConfigs = append(taskConfigs, taskConfig)
This is the only change. Once we find a file, see if it is an airplane task using the task discovers. If it is, convert to a task config

2021-12-09 03:55 UTC, leeweisberger commented on pkg/cmd/tasks/deploy/discover/script_discover.go
> +package discover
This code is copy pasted. This is how we discover script (lite) airplane tasks

2021-12-09 03:57 UTC, leeweisberger commented on pkg/taskdir/definitions/validate.go
> +	return fmt.Sprintf("invalid YAML format: %v", err.Errors)
Including the json schema error. We might want to format differently, but this is more useful than just barfing. I used this when writing tests to figure out what was wrong with my yaml.

2021-12-09 21:57 UTC, francescaleung requested changes
We should also make sure that discovery detects duplicate tasks (e.g., your script is still comment-linked but you also have a task defn file). Your choice whether to handle that in this PR or a separate one.

2021-12-09 21:57 UTC, francescaleung commented on pkg/cmd/tasks/deploy/predeploy.go
> +func ensureConfigsExist(ctx context.Context, client api.APIClient, def definitions.Definition) error {
hmm this should get changed to a DefinitionInterface, make sure everyone's calling it

2021-12-09 21:59 UTC, leeweisberger commented on pkg/cmd/tasks/deploy/discover/discover.go
> +				return nil, err
Yeah I have to merge in your changes here

2021-12-09 22:47 UTC, leeweisberger commented on pkg/cmd/tasks/deploy/deploy_tasks.go
> +	utr, err := tc.Def.UpdateTaskRequest(ctx, client, image)
Are you saying I should remove it and change image -> nil... and that's it?

2021-12-09 22:49 UTC, leeweisberger commented on pkg/cmd/tasks/deploy/deploy_tasks.go
> +	utr.Permissions = tc.Task.Permissions
Can you explain? Are you saying that the taskConfig won't have these values and we shouldn't overwrite the values in the utr? I don't understand

2021-12-09 22:51 UTC, leeweisberger commented on pkg/cmd/tasks/deploy/predeploy.go
> +func ensureConfigsExist(ctx context.Context, client api.APIClient, def definitions.Definition) error {
I didn't change this - you're saying that it was just wrong in the first place? It should be an interface and we should call it before deploying? What's the purpose of this (I'm not really following)

2021-12-09 22:51 UTC, leeweisberger commented
I added back the "task doesn't exist behavior" here: https://github.com/airplanedev/cli/pull/345/commits/40a278702b3273bea2276f7be89151cd4c2fd77c

2021-12-10 14:45 UTC, francescaleung commented on pkg/cmd/tasks/deploy/deploy_tasks.go
> +	utr.Permissions = tc.Task.Permissions
I'm saying that the UpdateTaskRequest object coming out of Definition_0_3.GetUpdateTaskRequest will fill in these fields (because Definition_0_3 defines them) but the UpdateTaskRequest object coming out of Definition.GetUpdateTaskRequest won't. These lines mean any changes to permissions in a task defn won't get propagated, but not having these lines means that you lose any explicit permissions on tasks deployed by script.

2021-12-10 14:48 UTC, francescaleung commented on pkg/cmd/tasks/deploy/predeploy.go
> +func ensureConfigsExist(ctx context.Context, client api.APIClient, def definitions.Definition) error {
This function appears to be called only from deploy-from-yaml, which kind of makes sense since deploy-from-script doesn't have the ability to specify configs. But deploy-from-defn does, so maybe it should get called at least for deploy-from-defn.

2021-12-10 15:34 UTC, francescaleung commented on pkg/cmd/tasks/deploy/deploy_tasks.go
> +	utr, err := tc.Def.UpdateTaskRequest(ctx, client, image)
```suggestion
	utr, err := tc.Def.GetUpdateTaskRequest(ctx, client)
	...
	if image != nil {
		utr.Image = image
	}
```

2021-12-10 15:43 UTC, francescaleung requested changes
Looking good, concerns from first review still applicable though

2021-12-10 15:43 UTC, francescaleung commented on pkg/cmd/tasks/deploy/discover/discover.go
> +					} else if task.ID == "" {
maybe HandleMissingTask should return a pointer instead, so this can be a nil check

2021-12-10 16:55 UTC, leeweisberger commented on pkg/cmd/tasks/deploy/predeploy.go
> +func ensureConfigsExist(ctx context.Context, client api.APIClient, def definitions.Definition) error {
Updated. I didn't understand what the function was doing - I gave it a slight rename

2021-12-10 16:58 UTC, leeweisberger commented on pkg/cmd/tasks/deploy/discover/discover.go
> +					} else if task.ID == "" {
Good call. Done

2021-12-10 22:45 UTC, francescaleung requested changes

2021-12-10 22:45 UTC, francescaleung commented on pkg/cmd/tasks/deploy/deploy_tasks.go
> +	utr.Permissions = tc.Task.Permissions
This still needs to be addressed!

2021-12-10 22:59 UTC, leeweisberger commented on pkg/cmd/tasks/deploy/deploy_tasks.go
> +	utr.Permissions = tc.Task.Permissions
Missed this.

How's this: https://github.com/airplanedev/cli/pull/345/commits/dba6976678f51831078181102686f2850f1c07a4

When you finish the permissions todo, you can write a test for this

2021-12-10 23:13 UTC, francescaleung commented on pkg/cmd/tasks/deploy/deploy_tasks.go
> +	utr.Permissions = tc.Task.Permissions
Doesn't this fail if you're moving from explicit permissions to no explicit permissions?

2021-12-10 23:21 UTC, leeweisberger commented on pkg/cmd/tasks/deploy/deploy_tasks.go
> +	utr.Permissions = tc.Task.Permissions
Ugh you're right. I think the only way to do it then is to pass in the current state and make the call in the update fn

2021-12-10 23:26 UTC, leeweisberger commented on pkg/cmd/tasks/deploy/deploy_tasks.go
> +	utr.Permissions = tc.Task.Permissions
I don't think it's that bad: https://github.com/airplanedev/cli/pull/345/commits/a9a6fee57efad7a85a9af6edc3aa3bd1b3136d77

2021-12-13 16:01 UTC, francescaleung approved these changes

2021-12-13 17:24 UTC, merged