Run deploys from CLI
airplanedev/cli pull request #378
Opened 2022-02-02 16:20 UTC by leeweisberger

Rather than creating builds and updating tasks, we now:
1. Discover airplane tasks.
2. Tar and upload tasks that need to be built.
3. Collect git metadata about the deploy.
4. Create a deploy.
5. Log deploy logs and wait for the deploy to complete.

---
There is one piece of complexity here - technically someone can deploy tasks that are part of different git repos. We store git metadata on the deploy and I think it generally makes sense here for the product. I decided, at least for now, to detect if there are tasks from multiple git repos in one deploy, log a message to sentry, and not include git metadata on the deploy. If we have to, we could move git metadata onto individual tasks. I imagine this will be very uncommon.

This will officially launch deploys, so I have to make sure everything is working downstream before I merge this.

2022-02-02 16:21 UTC, leeweisberger commented on pkg/analytics/analytics.go
> +func CaptureMessage(msg string) {
@colinking I don't think we use this anywhere - I just want a log so I can track how often unexpected things happen. We don't have any other logging system hooked up (just sentry and segment). Thoughts on this?

2022-02-02 16:21 UTC, leeweisberger commented on pkg/api/client.go
> +	GetDeployLogs(ctx context.Context, deploymentID string, prevToken string) (res GetDeployLogsResponse, err error)
We are now dealing with deploys, not builds!

2022-02-02 16:22 UTC, leeweisberger commented on pkg/build/local.go
> +func (d *registryTokenGetter) getRegistryToken(ctx context.Context, client api.APIClient) (registryToken api.RegistryTokenResponse, err error) {
I moved this from build/remote.go (which is now deleted). No other change

2022-02-02 16:23 UTC, leeweisberger commented on pkg/build/mocks.go
> -		BuildID:  "buildID",
We are only creating builds locally, and no build id is produced

2022-02-02 16:24 UTC, leeweisberger commented on pkg/cmd/tasks/deploy/git.go
> +type GitRepoGetter interface {
I moved git functions here and put GetGitRepo behind an interface so we can mock it out for testing

2022-02-02 16:24 UTC, leeweisberger commented on pkg/cmd/tasks/deploy/git.go
> +func GetGitMetadata(repo *git.Repository) (api.GitMetadata, error) {
No changes to this function. Just moved

2022-02-02 16:25 UTC, leeweisberger commented on pkg/cmd/tasks/deploy/deploy_tasks.go
> +		gitRoots = append(gitRoots, gitRoot)
This only exists for the case I talked about in the pr description - if tasks from multiple git repos are deployed together, drop git metadata

2022-02-02 16:26 UTC, leeweisberger commented on pkg/cmd/tasks/deploy/deploy_tasks.go
> +	// TODO log URL to deploy
We're going to log the URL to the deploys page that @rose-huang is building when that is ready

2022-02-02 16:28 UTC, leeweisberger commented on pkg/cmd/tasks/deploy/deploy_tasks.go
> +func (d *deployer) tarAndUploadTasks(ctx context.Context, taskConfigs []discover.TaskConfig) (map[string]string, error) {
None of this tarring and uploading stuff is new - It's just taken from remote.go (which was deleted). I copy and pasted it and made slight modifications

2022-02-02 16:28 UTC, leeweisberger commented on pkg/cmd/tasks/deploy/deploy_tasks.go
> +func waitForDeploy(ctx context.Context, loader logger.Loader, client api.APIClient, deploymentID string) error {
This was also copied from remote.go, just updated from `waitForBuild` to `waitForDeploy`

2022-02-02 16:29 UTC, leeweisberger commented on pkg/cmd/tasks/deploy/deploy_tasks.go
> +func deployLog(ctx context.Context, level api.LogLevel, loader logger.Loader, req deployLogReq, args ...interface{}) {
Also copied from remote.go.

2022-02-02 16:29 UTC, leeweisberger commented on pkg/cmd/tasks/deploy/deploy_tasks.go
> +func confirmBuildRoot(root string) error {
Copied from remote.go. Didn't make any changes to this

2022-02-03 21:05 UTC, francescaleung approved these changes

2022-02-04 15:04 UTC, leeweisberger commented on pkg/analytics/analytics.go
> +func CaptureMessage(msg string) {
We actually don't initialize a sentry client if the user hasn't opted in, so this will be a no-op

2022-02-04 18:44 UTC, colinking requested changes
Let's chat about how this impacts folks on the legacy YAML format.

2022-02-04 18:44 UTC, colinking commented on pkg/api/client.go
> +	CreateDeploy(ctx context.Context, req CreateDeployRequest) (CreateDeployResponse, error)
`CreateDeploy / GetDeployment` are inconsistent. IIRC `Deployment` is the noun here? Let's update the API before releasing this.

2022-02-04 18:44 UTC, colinking commented on pkg/api/client.go
> +	err = c.do(ctx, "GET", "/deploys/getLogs?"+q.Encode(), nil, &res)
There's a helper for query params (`encodeQueryString`) that filters out empty string values.

2022-02-04 18:44 UTC, colinking commented on pkg/analytics/analytics.go
> +func CaptureMessage(msg string) {
Neat, didn't know about Sentry messages.

Minor: `ReportMessage` to match `ReportError`? 😇

2022-02-04 18:44 UTC, colinking commented on pkg/api/types.go
> +	Env               libapi.TaskEnv           `json:"env"`
Can you rename this to `EnvVars`? Since we're introducing environments, it no longer is clear this refers to environment variables. We'll make this change in our existing APIs down the road.

2022-02-04 18:44 UTC, colinking commented on pkg/cmd/tasks/deploy/yaml.go
> -			bc = build.NewRemoteBuildCreator(archive.NewAPIArchiver(&logger.StdErrLogger{}, cfg.client, &archive.HttpUploader{}))
This is a breaking change -- anyone using the legacy YAML format will no longer be able to do their builds remotely. Was that intended?

2022-02-04 18:44 UTC, colinking commented on pkg/cmd/tasks/deploy/deploy_tasks.go
>  	if len(d.cfg.changedFiles) > 0 {
This function is rather large -- consider splitting out some of the logic into separate functions, e.g. `filterTasks()`. Should make this easier to skim.

2022-02-04 21:51 UTC, leeweisberger commented on pkg/cmd/tasks/deploy/yaml.go
> -			bc = build.NewRemoteBuildCreator(archive.NewAPIArchiver(&logger.StdErrLogger{}, cfg.client, &archive.HttpUploader{}))
Gar this was unintentional. I added back the remote build creator b/c I don't want to put in the work to convert legacy yaml -> deploys... Once we launch our other task yaml I think we should push to get rid of this cc @francescaleung

2022-02-04 22:09 UTC, leeweisberger commented on pkg/api/client.go
> +	CreateDeploy(ctx context.Context, req CreateDeployRequest) (CreateDeployResponse, error)
My thinking here was that Deploy is the process and Deployment is the resource. CreateDeploy kicks off the deploy process (and as part of that, creates a deployment resource) while GetDeployment just gets the resource. 

If that's confusing we can either
a) call everything Deployment
b) Change the endpoint to TriggerDeploy or something like that?

thoughts?

2022-02-07 15:59 UTC, leeweisberger commented on pkg/api/client.go
> +	CreateDeploy(ctx context.Context, req CreateDeployRequest) (CreateDeployResponse, error)
Yeah the more I think of it this is probably confusing and we should probably move to a)

2022-02-07 20:13 UTC, leeweisberger commented on pkg/api/client.go
> +	CreateDeploy(ctx context.Context, req CreateDeployRequest) (CreateDeployResponse, error)
I moved over to a

2022-02-08 16:14 UTC, colinking approved these changes

2022-02-08 20:16 UTC, merged