Implement airplane runtime httpd
airplanedev/cli pull request #424
Opened 2022-03-10 15:00 UTC by ericliuche

Adds the following functionality
```
  airplane httpdexec cmd [--port] [--host] [cmd_args...] [flags]
```
The `httpdexec` starts an http server that implements the airplane runtime. The airplane runtime is a lightweight server that communicates with a user command. The server supports the following
- a POST to `/` will execute the command, can optionally provide arguments for the command to run, and stream outputs e.g. `curl -i localhost:6000/ -X POST -d '{"args":["new echo", "1"], "env": {"TEST_ENV_VARIABLE":"hi"}}'`
- a POST to `/cancel` will SIGKILL the existing process if there is one

To see example behavior, start server with `go run ./cmd/airplane httpdexec --httpdhost localhost --debug pkg/cmd/httpd/test.sh`

Run ` curl -i localhost:6000/ -X POST -d '{}'` to see outputs with default arguments

Run ` curl -i localhost:6000/ -X POST -d '{"args":["new echo", "1"], "env": {"TEST_ENV_VARIABLE":"hi"}}'` to see outputs with provided arguments

Run ` curl -i localhost:6000/ -X POST -d '{}'` and then `curl -i localhost:6000/cancel -X POST` to see cancelled run

2022-03-10 15:28 UTC, ericliuche commented on pkg/cmd/httpd/cmdexecutor.go
> +	ExitStatus chan error
This could just all be combined into an Output message. I realized that right now the big issue with splitting them up is that the order of the lines can be mixed up

2022-03-10 15:53 UTC, zhan-airplane requested changes
Overall, I think my main impression is that the code should end up being neater if we combine the execute and getoutputs endpoints (i.e. execute is long lasting and returns outputs over time, closing the connection when the command exits) - the execute can spin up goroutines for reading stderr/stdout maybe, but exit status can go in the main loop and also we keep a lot less strange global state around. I think it's OK to keep this long-lived connection around because it's intended to only go through localhost anyway

LMK if there's a reason why you didn't go with that route haha

2022-03-10 15:53 UTC, zhan-airplane commented on pkg/cmd/httpd/httpd.go
> +	shutdownTimeoutDuration = 10 * time.Second
nit: I have a slight preference for keeping this `const` in the same file as where it's used, if possible

2022-03-10 15:53 UTC, zhan-airplane commented on pkg/cmd/httpd/httpd.go
> +		PersistentPreRunE: utils.WithParentPersistentPreRunE(func(cmd *cobra.Command, args []string) error {
We don't actually need to be logged in for this right?

2022-03-10 15:53 UTC, zhan-airplane commented on pkg/cmd/httpd/cmdexecutor.go
> +// NOCOMMIT should we add a unique exec id used to track command executions?
Eh we can add it when we need it right? Unless you have a use case for it right now

2022-03-10 15:53 UTC, zhan-airplane commented on pkg/cmd/httpd/server.go
> +// NOCOMMIT check that hanging forever the right behavior
Hmm actually I was thinking that maybe we should just just combine the `getOutputs` endpoint with the `execute` endpoint - i.e. the execute endpoint doesn't return immediately, but sticks around and writes contents back until the process exits

2022-03-10 15:53 UTC, zhan-airplane commented on pkg/cmd/httpd/server.go
> +				flusher.Flush()
Also, maybe we can return right after we receive the exit status? No point keeping things around after that right?

2022-03-10 15:53 UTC, zhan-airplane commented on pkg/cmd/httpd/cmdexecutor.go
> +	go c.Wait()
If we merge the execute and get-outputs endpoints, we can do this synchronously instead of asynchronously (i.e. then we don't need to run this in a goroutine)

2022-03-10 15:53 UTC, zhan-airplane commented on pkg/cmd/httpd/cmdexecutor.go
> +		c <- scanner.Text()
If this channel is full, the outputs will be left waiting on the pipe itself right? which I don't think should be a huge problem haha

2022-03-10 15:53 UTC, zhan-airplane commented on pkg/cmd/httpd/cmdexecutor.go
> +				logger.Log("unable to signal, command already exited")
I think if the execute endpoint is synchronous it also answers this question - these errors can pass all the way back into the execute handler and we can deal with it then

2022-03-10 15:53 UTC, zhan-airplane commented on pkg/cmd/httpd/cmdexecutor.go
> +			c.ExitStatus <- err
Exit status should only pass back once per execution right? would be spooky if the channel gets full haha

2022-03-10 15:53 UTC, zhan-airplane commented on pkg/cmd/httpd/cmdexecutor.go
> +	// when there isn't an active command?
Hmm IMO if we combine the get-output and execute endpoints, then that answers this question more cleanly - we can just pass these channels in the args and not keep them around this global struct. We still need to keep `ActiveCmd` around for cancellation, but that's much more straightforward to think about

2022-03-10 15:58 UTC, zhan-airplane commented on pkg/cmd/httpd/cmdexecutor.go
> +	ExitStatus chan error
In general you can't really determine the order of `stdout` and `stderr` reliably IIRC. Exit status should definitely go at the end though haha

2022-03-10 16:32 UTC, ericliuche commented on pkg/cmd/httpd/cmdexecutor.go
> +			c.ExitStatus <- err
this was in the case of being able to have multiple executions

2022-03-10 16:33 UTC, zhan-airplane commented on pkg/cmd/httpd/cmdexecutor.go
> +			c.ExitStatus <- err
Even if we have multiple executions, we should have different channels for each execution anyway

2022-03-10 17:44 UTC, zhan-airplane commented on pkg/cmd/httpd/server.go
> +		exitStatus, err := cmdExecutor.Wait()
Yeah I'm ok with it personally

2022-03-10 19:25 UTC, zhan-airplane commented on pkg/cmd/httpd/cmdexecutor.go
> +	// NOCOMMIT: should we try to kill if interrupt doesn't take down the process?
Also OK with punting checking if the cmd is actually killed to another PR

2022-03-10 22:29 UTC, ericliuche commented on pkg/cmd/httpd/cmdexecutor.go
> +	if c.ActiveCmd == nil {
ah yeah you're right. man i haven't used my multithreaded brain in so long lol

2022-03-10 22:34 UTC, ericliuche commented on pkg/cmd/httpd/server.go
> +		if err := json.NewEncoder(w).Encode(output); err != nil {
added a mutex to be sure

2022-03-11 02:23 UTC, ericliuche commented on pkg/cmd/httpd/server.go
> +		if err := json.NewEncoder(w).Encode(output); err != nil {
So here, `WriteOutput` is called once for stderr, and once for stdout. The behavior i want to achieve is 
1. If either `WriteOutput` fails, e.g. `Encode` or `scanner` have an error, i want the other `WriteOutput` to also stop. I tried doing this with a `context` but had trouble writing this function in such a way that a `<-ctx.Done()` can stop it.
2. if either `WriteOutput` fails, I want to surface that error back to the client. right now the exist status is coming from `exitStatus := cmdExecutor.Wait()`, so somehow i need to get this error there, or approach it a different way. one way i tried doing this was creating a new `chan error` that `WriteOutput` could write to and `Wait` would consume. is that the right way?
3. it would be cool if anytime the request context `r.Context` finishes or `WriteOutput` errors, `Wait` would call `Cancel()` to terminate the child process and then pass on the `r.Context`/`WriteOutput` error in the ExitStatus, not sure how to accomplish that though :/

2022-03-11 02:51 UTC, ericliuche commented on pkg/cmd/httpd/cmdexecutor.go
> +	// NOCOMMIT: should we try to kill if interrupt doesn't take down the process?
its also not too obvious to me the right way to do that, the naive way of 

```
1. c.Signal <- os.Interrupt
2. sleep(1 second)
3. return if process exists
4. c.Signal <- os.Kill
```

has the main flaw that (1) and (4) could possibly kill two different calls to `Execute` if timed poorly

2022-03-11 04:03 UTC, ericliuche commented on pkg/cmd/httpd/server.go
> +		stdoutPipe, err := cmd.StdoutPipe()
actually i think the right way to do this might just be to implement our own `io.Writer` and se it to `cmd.Stdout`

2022-03-11 07:51 UTC, zhan-airplane requested changes
Hmm meta comment: I realize we probably should have taken time to talk this through and sketched out how we want the different goroutines, etc. to work before we started implementing it haha, let's take note for next time we have something fiddly like this (I didn't realize there were this many pitfalls up front, my bad)

Anyway, I think there are two main high-level changes I'd like to make. LMK if you see any concurrency/etc issues with these, and then we can talk it through before actually coding haha to iron out bugs more quickly

1) I think the way the execute endpoint should be set up is, you set up three channels (`doneC`, `errC`, `logsC`), which are shared between two scanner goroutines. 
* The scanner goroutines call `scanner.Scan()` in a loop and write strings to `logsC` (this handles any messiness between `stderr` and `stdout` racing). If any of them throw an error, it writes to `errC` and exits. If they exit correctly, they write to `doneC`. 
* The main thread listens on all 3 channels simultaneously, and 1) if it receives something on `logsC`, it writes it via http, 2) if it receives something on `errC`, it kills the process and closes the pipes, 3) if it receives two messages on `doneC` (one from each scanner), it calls `Wait()` on the main `Cmd` and then pulls the exit code.

2) Let's assign an ID to each execution after all (good callout about this earlier, I was wrong haha; just generate it via UUID or something I guess), and store a map of ID to `CmdExecutor` (we should guard this map with a mutex).
* Cancellations that receive an ID cancel only that execution
* Cancellations that don't receive an ID pull the first execution off the map and cancel that.
* Let's not have restrictions on being only allowed to run one command at a time on this level - we'll handle this restriction on the runner level instead
* Signals we catch can be passed directly to every executor in the map. Cancellation signals just pass to one specific executor
* We can do the interrupt -> kill cancellation this way cleanly without any weird races.

2022-03-11 07:51 UTC, zhan-airplane commented on pkg/cmd/httpd/cmdexecutor.go
> +		return &NoExistingCmdError{}
You need to unlock here when returning :P

2022-03-11 07:51 UTC, zhan-airplane commented on pkg/cmd/httpd/cmdexecutor.go
> +	case c.Signal <- os.Kill:
Actually now you mention it, there's a race condition here right? Like, we could accidentally execute an entirely new command and then have it be cancelled by a slow cancellation...

Maybe execution IDs is a good idea after all haha, like we'd generate one when we first call execute and return that, then if it's provided to the cancel handler we only cancel if it's the correct run. That might solve the broader problem too, where instead of having a global `CmdExecutor`, we have a map of ID -> `CmdExecutor` and then we don't have this strangeness around multiple runs (if the cancel handler doesn't receive an execution ID we just grab the first one in the map I guess)

2022-03-11 07:51 UTC, zhan-airplane commented on pkg/cmd/httpd/server.go
> +		exitStatus := cmdExecutor.Wait()
I'm not entirely sure this is doing the right thing actually? According to the `exec` documentation (https://pkg.go.dev/os/exec#example-Cmd.StdoutPipe), `It is thus incorrect to call Wait before all reads from the pipe have completed`.

Looks like maybe you should be doing something like https://github.com/golang/go/issues/38268#issuecomment-609562062, where you have a waitgroup on the two `WriteOutput` goroutines, and only wait on the process once the two `WriteOutput` calls exit

2022-03-11 07:51 UTC, zhan-airplane commented on pkg/cmd/httpd/server.go
> +		if err := json.NewEncoder(w).Encode(output); err != nil {
Actually just remembered, Colin linked this to me:

> [Don't communicate by sharing memory, share memory by communicating.](https://www.youtube.com/watch?v=PAAkCSZUG1c&t=2m48s)

Instead of having a mutex here, maybe the two sides should write to a shared channel and we should have a third goroutine reading off the end and sending outputs that way.

Would be nice if the cancellation thing could also work the same way haha, but I think if we go with a map of ID->executor approach we'd need a mutex on the top level, so oh well

2022-03-11 16:26 UTC, ericliuche commented on pkg/cmd/httpd/server.go
> +			Type:        OutputTypeStdout,
should this be a different OutputType?

2022-03-11 17:56 UTC, zhan-airplane approved these changes

2022-03-11 17:56 UTC, zhan-airplane commented on pkg/cmd/httpd/server.go
> +			Type:        OutputTypeStdout,
Yeah let's make it something different, like `OutputTypeMetadata` or `OutputTypeSystem` or something

2022-03-11 17:56 UTC, zhan-airplane commented on pkg/cmd/httpd/server.go
> +		outputDoneC := make(chan interface{}, 2)
Let's add some comments for what these channels are

2022-03-11 17:56 UTC, zhan-airplane commented on pkg/cmd/httpd/server.go
> +		}); err != nil {
Let's log this error too

2022-03-11 17:56 UTC, zhan-airplane commented on pkg/cmd/httpd/server.go
> +		}); err != nil {
Actually, can we return these errors via http too? So that our runner can deal with them

2022-03-11 17:56 UTC, zhan-airplane commented on pkg/cmd/httpd/cmdexecutor.go
> +	activeCmdMutex *sync.Mutex
We don't need this mutex any more now right?

2022-03-11 17:56 UTC, zhan-airplane commented on pkg/cmd/httpd/cmdexecutor.go
> +	activeCmdMutex *sync.Mutex
Since it's not global any more, we don't even need to check if `ActiveCmd` exists when cancelling, we can just yolo and send the kill signal (I guess it won't return an error if it's not running, but I think that's ok - the end result state is the same anyway)

2022-03-11 17:56 UTC, zhan-airplane commented on pkg/cmd/httpd/cmdexecutor.go
> +			logger.Log("closed output")
We probably can get rid of some of these log statements haha

2022-03-11 17:56 UTC, zhan-airplane commented on pkg/cmd/httpd/cmdexecutor.go
> +			if outputDoneCount == cap(outputDoneC) {
We should document somewhere (maybe on the comment for this channel?) that we're expecting the cap to be the number of dones we're looking for

2022-03-11 19:50 UTC, merged