Add loader to stderrorlogger
airplanedev/cli pull request #430
Opened 2022-03-17 15:47 UTC by leeweisberger

Add the loader to the logger itself so we don't have to keep manually starting and stopping the loader. The loader automatically stops and restarts every time something is logged. This prevents the loader from appearing during a log.

2022-03-17 21:17 UTC, francescaleung requested changes
Looking good, just a few missed calls

2022-03-17 21:17 UTC, francescaleung commented on pkg/cmd/tasks/deploy/deploy.go
> -
The loader was removed here but I think this still needs it, as it's not using the logger

2022-03-17 21:17 UTC, francescaleung commented on pkg/cmd/tasks/deploy/predeploy.go
>  		confirmed, errc := utils.Confirm("Create it now?")
I suspect this will also need the loader to be removed

2022-03-17 21:17 UTC, francescaleung commented on pkg/logger/logger.go
> +// NewStdErrLogger creates a new logger taht logs to stderr.
```suggestion
// NewStdErrLogger creates a new logger that logs to stderr.
```

2022-03-17 21:17 UTC, francescaleung commented on pkg/cmd/tasks/deploy/yaml.go
> +	defer l.StopLoader()
there are other `logger.*` calls in this file that should probably be `l.*` calls instead

2022-04-20 18:48 UTC, leeweisberger commented on pkg/cmd/tasks/deploy/deploy.go
> -
Manually stopped the loader before all calls to confirm. We probably also want to add this onto the logger, but didn't do that in this pr

2022-04-21 17:14 UTC, leeweisberger commented on pkg/api/client.go
> -	CreateBuild(ctx context.Context, req CreateBuildRequest) (res CreateBuildResponse, err error)
This is unrelated - we are no longer using remote.go or any code related to builds. Rather than upgrade it with the new logger loader I just deleted

2022-04-22 15:49 UTC, francescaleung approved these changes

2022-04-22 21:46 UTC, merged