Discover, tar, and deploy apps
airplanedev/cli pull request #463
Opened 2022-04-26 20:55 UTC by leeweisberger

## Description
Discover apps (behind a flag).

Once discovered, tar and upload app content (same as we do for tasks).

Add discovered apps to a deployment along with the url of the uploaded content.

## Test plan
Tested locally. Some unit tests added.

2022-04-26 20:56 UTC, leeweisberger commented on pkg/cmd/tasks/deploy/deployer.go
> +	}
This is generally copied from tasks code

2022-05-05 17:41 UTC, stepzhou requested changes
Requesting for my entrypoint question

2022-05-05 17:41 UTC, stepzhou commented on pkg/cmd/tasks/deploy/deployer.go
> +		}
Is this doing anything?

2022-05-05 17:41 UTC, stepzhou commented on pkg/cmd/tasks/deploy/deployer.go
>  	// If tasks in a single deploy come from different git repos, we do not
tasks or apps

2022-05-05 17:41 UTC, stepzhou commented on pkg/cmd/tasks/deploy/deployer.go
> +		repo, err = d.repoGetter.GetGitRepo(ac.Entrypoint)
I'm confused what this Entrypoint is. I thought the app entrypoints were that gcs:// string. Is this entrypoint different?

2022-05-05 17:46 UTC, stepzhou commented on pkg/cmd/tasks/deploy/deployer.go
> +		repo, err = d.repoGetter.GetGitRepo(ac.Entrypoint)
Oh I get it. This entrypoint is the path that's defined in the app definition yaml file. The terminology here is really confusing

2022-05-05 17:46 UTC, stepzhou approved these changes

2022-05-05 22:50 UTC, leeweisberger commented on pkg/cmd/tasks/deploy/deployer.go
> +		repo, err = d.repoGetter.GetGitRepo(ac.Entrypoint)
I just removed entrypoint. I have no clue whether it's going to be useful. We can decide later.

2022-05-05 23:56 UTC, merged