[WIP/RFC] Fill in additional files needed for airplane views dev
airplanedev/cli pull request #512
Opened 2022-06-29 15:41 UTC by zhan-airplane

## Description
Putting up a PR first just to play with various settings + so it's a little easier to have something to talk about or dev on.

Basically, this expects an `App.tsx` file and optionally a `package.json` file (will patch a whole bunch of dependencies/etc on the `package.json`), and copies them to a temp dir plus writes a whole bunch of other files out, then runs `npm install` and `npm run dev` in that directory.

There's a `viewdir.ViewDirectory` struct somewhere that when we figure out what the `.view.yaml` should contain, can do all the relevant parsing.

Some of the files here should probably be in `airplanedev/lib`, but I'm putting them here just so it's easy to play with them all in one place

## Test plan
Ran locally (`/home/zhan/cli/main --host api.airplane.so:5000 views dev --local-views /home/zhan/views`) in a directory containing an `App.tsx` copied from the views repo

---
cc @leeweisberger @stepzhou

2022-06-29 18:35 UTC, zhan-airplane commented
@stepzhou @leeweisberger FYI originally put rose as reviewer on this PR but adding the two of you as well since after talking we weren't sure about some of the vite stuff (e.g. whether all the stuff in `main.tsx` makes sense, whether the vite config is set up correctly)

2022-06-29 23:08 UTC, leeweisberger commented on cmd/airplane/views/dev/dev.go
> +	cmd := exec.Command("npm", "install")
We do want to determine if they're using npm or yarn.

We also don't currently enforce this today in tasks - we expect the user to run this on their own. I think I'm in favor of doing this

2022-06-29 23:18 UTC, leeweisberger requested changes
generally like the approach!

Let's discuss a bit what we want the user to have possible control over and what we want to take from them. I think we should go with a "overwrite only if the user has not specified their own way" approach. e.g. if the user has their own `dev` command, don't override with our own.

2022-06-29 23:18 UTC, leeweisberger commented on cmd/airplane/views/dev/dev.go
> +	deps["@airplane/views"] = "*"
I feel like it's ok to enforce that the user has this. Especially @airplane/views. We want the user to explicitly choose the version of the views lib as it will change - I don't think we can auto upgrade them

2022-06-29 23:18 UTC, leeweisberger commented on cmd/airplane/views/dev/dev.go
> +	}
What is this for? Don't see how this is useful?

2022-06-29 23:18 UTC, leeweisberger commented on cmd/airplane/views/dev/dev.go
> +	devDeps["@types/react-dom"] = "^18.0.0"
Adding these at dev time means you don't get ts support when you'r authoring, so I tend to think it's ok to enforce this as well.

2022-06-29 23:18 UTC, leeweisberger commented on cmd/airplane/views/dev/dev.go
> +	devDeps["vite-tsconfig-paths"] = "^3.5.0"
I would check to see if these are already in the user's package.json. we only want to add them if they don't already exist

2022-06-29 23:18 UTC, leeweisberger commented on cmd/airplane/views/dev/dev.go
> +	scripts["dev"] = "vite"
We don't need there to be a script called dev - we could just run `vite` without a script in the package.json. But I kind of like this change IF we only do this if the user doesn't include their own `dev` script. So if the user has a `dev` script, we call that. Else we replace it with the default `vite`

2022-06-29 23:18 UTC, leeweisberger commented on cmd/airplane/views/dev/dev.go
> +					"@airplane/views": "@airplane/views/lib/src/index.ts",
These guys we aren't going to need. We just have this in `apps` because it contains both the view and the lib in a yarn workspace.

2022-06-29 23:18 UTC, leeweisberger commented on cmd/airplane/views/dev/dev.go
> +	if err := os.WriteFile(indexHtmlPath, []byte(heredoc.Doc(`
Generally like this + main.tsx

2022-06-29 23:18 UTC, leeweisberger commented on cmd/airplane/views/dev/dev.go
> +					<Container size="xl" py={96}>
This is pretty cool because we can completely control the chrome of the dev experience. Right now we just place the view in a container - in the future we might add more ux around it

2022-06-29 23:18 UTC, leeweisberger commented on cmd/airplane/views/dev/dev.go
> +	cmd.Flags().StringVar(&cfg.LocalViews, "local-views", "", "If set, overrides the @airplane/views package with a local directory.")
I don't think we need this - can you explain why you added?

2022-06-29 23:19 UTC, leeweisberger commented on cmd/airplane/views/dev/dev.go
> +	cmd := exec.Command("npm", "install")
Another issue here is that we actually need to write a package.json to the user's machine, or else this is going to take a long time every time we run it!

2022-06-30 16:25 UTC, zhan-airplane commented on cmd/airplane/views/dev/dev.go
> +	}
Ah it's mainly for our development - I was trying to find a way to use a local version of the views library rather than a downloaded one.

2022-06-30 16:30 UTC, zhan-airplane commented on cmd/airplane/views/dev/dev.go
> +	deps["@airplane/views"] = "*"
Ah I agree with your later comment about not overwriting if the users have provided it, but I don't think we should require users to have some version of `@airplane/views` set inside their `package.json` for this to work - it's quite possible for them to write a view that doesn't import `@airplane/views` at all, and they'd only need this because we're adding our own stuff inside `main.tsx`. In that case, it'd be fairly natural for someone to conclude that they should just delete it from their deps list.

2022-06-30 16:40 UTC, zhan-airplane commented on cmd/airplane/views/dev/dev.go
> +	scripts["dev"] = "vite"
I'm just going to take it out, and call vite from `node_modules/.bin/`

2022-06-30 22:23 UTC, leeweisberger commented on cmd/airplane/views/dev/dev.go
> +	cmd := exec.Command("npm", "install")
Let's discuss in person! Basically yarn/npm install download a bunch of stuff to node_modules on the users machine and additionally cache stuff in files. We actually have to write files to the users machine, not just a temp dir that will be deleted. I'm actually not positive that's not what we're doing, but it seems like it is?

2022-07-06 09:58 UTC, zhan-airplane commented
@leeweisberger I decided to generate a consistent hash of the view directory struct to create a consistent temp dir that isn't deleted, in place of having some kind of `.airplane` cache dir in the original dir itself, to avoid weird symlinking cycle issues. Should still work basically the same way (i.e. as long as you only change code inside the view, rerunning dev will try to reuse the previously-generated temp dir if it exists, which'll effectively cache `node_modules` and everything else there)

2022-07-06 21:37 UTC, leeweisberger approved these changes
Let's start getting this checked in so we can iterate
1. We want to move most of this to lib
2. We want to pull out the shim stuff into its own .tsx files so they're easier to develop
3. Is there a good way to manage our dependency versions (e.g. vite). Can we use renovate somehow?
4. We are going to have to make a bunch of changes to ensure this works correctly with yarn workspaces (can probably ignore for now)

I don't loooove hiding files in some tmp directory - would rather be explicit about where we are putting this stuff to a) avoid writing to random parts of the user's system and b) so there's less magic. We can do this for now / open to discuss it.

2022-07-06 21:37 UTC, leeweisberger commented on cmd/airplane/views/dev/dev.go
> +			<title>TODO</title>
Replace TODO with `Airplane` or something for now. Maybe the view slug if that's easy

2022-07-06 21:37 UTC, leeweisberger commented on cmd/airplane/views/dev/dev.go
> +						<Stack direction="column">
I actually don't really think this is going to do anything b/c there is only one child (App). Let's delete

2022-07-06 21:37 UTC, leeweisberger commented on cmd/airplane/views/dev/dev.go
> +		"vite-tsconfig-paths":  "^3.5.0",
We aren't using this, delete

2022-07-07 09:40 UTC, merged