Create tasks gentypes command
airplanedev/cli pull request #517
Opened 2022-07-05 15:35 UTC by leeweisberger

## Description
Create a new command `airplane tasks gentypes` that generates TypeScript types (in the future we could expand to other languages) for Airplane tasks.

If you provide no arguments, we generate a types file for all Node.js tasks. You can also provide a single task and we generate types for that task.

Two improvements we may want to make (I did not in this pr) is to 1) generate types for a task that has not been deployed yet and 2) generate types into the script file rather than an external file.

This command will be very helpful for Views (and probably also Workflows) where we want to know the type of various tasks.

depends on https://github.com/airplanedev/lib/pull/172

## Test plan
I manually ran this and generated a types file. Also pretty solid unit tests.

2022-07-05 22:52 UTC, colinking requested changes
LGTM, but I'd like to talk through how this will be used by users. Specifically, see my comment below about how this ties to the SDK.

2022-07-05 22:52 UTC, colinking commented on cmd/airplane/tasks/initcmd/init.go
> +	code, fileMode, err := r.Generate(apiTaskToRuntimeTask(task), runtime.GenerateOpts{GenerateComment: withComment})
🔥

2022-07-05 22:52 UTC, colinking commented on pkg/cmd/tasks/gentypes/gentypes.go
> +		Use:   "gentypes slug",
Could we call this `generate` instead? Maybe with an alias `gen` for conciseness.

2022-07-05 22:52 UTC, colinking commented on pkg/cmd/tasks/gentypes/gentypes.go
> +		Use:   "gentypes slug",
FWIW, I expect we'll generate runtime code at some point (e.g. logic to read resources from env vars).

2022-07-05 22:52 UTC, colinking commented on pkg/cmd/tasks/gentypes/gentypes.go
> +		Short: "Generates types for Node.js task parameters",
Would be nice to support Python as it has types built-in nowadays (cc @ameyakhare). For now, let's remove the reference to Node.js here and assume we'll add a Python implementation at some point.

```suggestion
		Short: "Generates types for task parameters",
```

2022-07-05 22:52 UTC, colinking commented on pkg/cmd/tasks/gentypes/gentypes.go
> +		if ok, err := utils.Confirm(fmt.Sprintf("Would you like to overwrite %s?", fileName)); err != nil {
nice

2022-07-05 22:52 UTC, colinking commented on pkg/cmd/tasks/gentypes/gentypes.go
> +		errors.Wrapf(err, "creating file %s", fileName)
...did our linter not error on this? hmm

```suggestion
		return errors.Wrapf(err, "creating file %s", fileName)
```

2022-07-05 22:52 UTC, colinking commented on pkg/cmd/tasks/gentypes/gentypes.go
> +		logger.Log("Generated TypeScript types")
Let's still print the file name here. If they didn't provide one, they won't know where the types are going to be produced after all.

2022-07-05 22:52 UTC, colinking commented on pkg/cmd/tasks/gentypes/gentypes.go
> +		logger.Log("Generated TypeScript types at %s", fileName)
Minor, but could you make the file name bold white? So it sticks out.

2022-07-05 22:52 UTC, colinking commented on pkg/cmd/tasks/gentypes/gentypes_test.go
> +						{Slug: "date-time", Type: libapi.TypeDatetime},
Invalid slug

```suggestion
						{Slug: "date_time", Type: libapi.TypeDatetime},
```

2022-07-05 22:52 UTC, colinking commented on pkg/cmd/tasks/gentypes/fixtures/multipletasks.ts
> +};
Can you include a newline between params? 🙏🏻

2022-07-05 22:52 UTC, colinking commented on pkg/cmd/tasks/gentypes/gentypes.go
> +	cmd.Flags().StringVar(&cfg.fileName, "file", "types.ts", "The file to save the generated types to.")
Assuming we eventually add Python support, this default value won't make sense. Maybe we drop the `--file` param entirely and just dump to stdout?

So you would do `airplane tasks gen > types.ts` instead.

2022-07-05 22:52 UTC, colinking commented on pkg/cmd/tasks/gentypes/gentypes.go
> +		tasksResp, err := apiClient.ListTasks(ctx, envSlug)
IMO, it would be more intuitive if this worked like `airplane deploy` and generated for all tasks in the current directory.

Same goes with accepting a YAML file path instead of a slug.

2022-07-05 22:52 UTC, colinking commented on pkg/cmd/tasks/gentypes/gentypes.go
> +		tasksResp, err := apiClient.ListTasks(ctx, envSlug)
I guess this has different semantics from `deploy` because users would use this to get type definitions for other tasks they can call?

If that's the primary use-case, I'd start thinking of this CLI command as generating a type-safe Airplane API client. At that point, it'd be nicer if this was more tightly integrated with the SDK. For example, if I call `airplane.execute("my_task")`, I'd want the return type to automatically have the correct types for `my_task`.

I was thinking about something similar within the context of resources. I want to generate runtime code + types that would allow you to access connected resources as `airplane.resources.db` (and TS would know `db` is, say, a PostgreSQL resource because of the types we generate from your task definition). We could do this code generation automatically during `airplane deploy`/`airplane dev` (and expose a `airplane gen` that would do this for you one-off). Possibly we do it similar to Prisma and produce the generated code into `node_modules`.

2022-07-05 22:52 UTC, colinking commented on pkg/cmd/tasks/gentypes/gentypes.go
> +		tasksResp, err := apiClient.ListTasks(ctx, envSlug)
If we tie this to the Airplane SDK, then I'd want the code generator to be part of the SDK. Otherwise, the code generator can fall out of line with the user's SDK version.

2023-01-12 23:53 UTC, leeweisberger commented
Gonna close. We'll get back to this soon.

2023-01-12 23:53 UTC, closed without merging