Fix log store synchronization
airplanedev/cli pull request #593
Opened 2022-08-19 07:01 UTC by calufornia

## Description

This PR fixes some issues with thread-safety when streaming logs to the previewer. Most notably, logs were dropped before due to a race condition where the executor was (attempting to) send logs through the log channel while the SSE handler was already processing a log - the log channel is an unbuffered channel (since we don't know how many logs the user's code will emit), and so during this processing, the executor couldn't send a log through the channel and would fallback to the default behavior of just appending it to the log store. We've fixed this by adding a wait group to ensure that the log has been processed by the SSE handler before sending another log to the channel.

In general, we don't want to block the execution of a command (which is why we use an unbuffered channel + non-blocking select), but we also want to support both the case when there's an SSE client connected and when there's not, which contributes to the complexity below.

There were also issues around log replay where the executor was appending logs to the log store as we were replaying past logs, which we've fixed by making replay occur inside the select in the SSE handler.

- The executor appends all logs to the log store, not just logs that aren't sent to the log channel receiver, and the SSE handler simply forwards these events.
- When replaying logs, simply send the logs to the same channel that the executor is sending logs to (this is also necessary to fix the synchronization issues mentioned above).

cc @kellymtrinh 

## Test plan
Tested the following scenarios with the previewer, with the following code:
```
export default async function(params) {
    for (let i = 0; i < 100; i++) {
        console.log(i);
        await new Promise(resolve => setTimeout(resolve, 100));
    }
}
```

1. Executed a task and viewed until completion.
2. Executed a task, navigated away, navigated back, viewed until completion.
3. Executed a task, navigated away, waited for completion, navigated back.

2022-08-19 07:06 UTC, calufornia commented on pkg/server/dev.go
> +			run.LogStore.WaitGroup.Done()
I think there's still technically a race condition here if the select clause doesn't become ready before the executor attempts to send another log through the channel. However, I haven't been able to reproduce this and seems likely because the log scanning done by the executor likely takes more time than moving to the next iteration of the for loop.

2022-08-19 14:38 UTC, colinking requested changes

2022-08-19 14:38 UTC, colinking commented on pkg/dev/dev.go
> +		}
@calufornia: Can we extract the log logic from the dev server? This should also make it easier to reason about race conditions in the logger (e.g. we can test it directly).

Here's a sketch. The idea is that the SSE endpoint just needs to listen on `Watch()` and doesn't need to be familiar with the implementation around the slice/channel. Ideally this would also support multiple watchers by giving each watcher their own channel.

```go
type LogWriter interface {
	// Record pushes a log into the store.
	Record(Log)
  // Close indicates that all logs have been written and that no more
	// logs are expected.
	Close()
}

type LogWatcher interface {
  // Watch streams logs through the channel. The channel is closed
  // once all logs have been streamed.
	Watch() <-chan Log
}

type LogStore struct {
	// ...
}

var _ LogWriter = &LogStore{}
var _ LogWatcher = &LogStore{}
```

2022-08-23 15:19 UTC, colinking commented on pkg/dev/logs.go
> +		LogChannel:  make(chan api.LogItem),
Buffering also helps avoid a dead lock:
1. A log watcher is created
2. The broker tries to replay logs to it
3. While replaying logs, the watcher shuts down (e.g. the request is closed).

(3) can't acquire the mutex since (2) is waiting for the watcher to pull logs from the channel.

This can still happen now if the number of logs to replay is >100.

2022-08-23 15:21 UTC, colinking commented on pkg/dev/logs.go
> +	Watchers map[LogWatcher]bool
Clarifies that the map value has no meaning.

```suggestion
	Watchers map[LogWatcher]struct{}
```

2022-08-23 15:47 UTC, colinking commented on pkg/dev/logs.go
> +		LogChannel:  make(chan api.LogItem),
There may be a solution here where the watcher tracks a "watermark" (indicating how far in `l.Logs` it has progressed) in a goroutine. The goroutine can then continuously push the next log into `LogsChannel` and this can block without issue if the channel is full, as long as it has a case that is checking if the watcher should close.

2022-08-23 22:26 UTC, calufornia commented on pkg/server/dev.go
>  			}
TIL channels optionally return an ok value - I think it'd probably be more like
```
case log, ok := <-watcher.LogChannel:
    if !ok {
        ...
```
but good catch!

2022-08-23 22:28 UTC, calufornia commented on pkg/dev/logs.go
> +		LogChannel:  make(chan api.LogItem),
Yeah the original motivation behind using an unbuffered channel was in the case that the log broker sends > n logs without the logs handler flushing (where n is the size of a buffered channel), which would result in logs getting dropped, but I imagine that case is probably rare.

2022-08-23 22:36 UTC, colinking commented on pkg/dev/logs.go
> +		LogChannel:  make(chan api.LogItem),
Hmm, I'm not sure I follow. An unbuffered channel doesn't allow you to send unlimited values -- it's the opposite! It will block until there is a receiver to accept the sent value. A buffered channel can send up to N items before blocking.

2022-08-23 23:04 UTC, merged