Search for dev config file in editor work directory
airplanedev/cli pull request #659
Opened 2022-09-15 19:14 UTC by calufornia

## Description

The CLI now attempts to automatically find a dev config file in the editor's dev root (i.e. the argument that's passed in to `airplane dev --editor [dev root]`). Previously, the CLI would attempt to look for a file called `airplane.dev.yaml` in the directory where the airplane CLI was being run - now, it looks in the dev root and traverses through parent directories until it reaches `/`. If none is found, the user is prompted to create one in the dev root. 

The user is prompted to create a dev config file only if they run `airplane dev` with the `--editor` flag - users are not prompted in the legacy usage of `airplane dev` (which generally does not require the dev config file).

## Test plan
```
➜  aplocal dev --editor ~/airplane/node_test
? Dev config file not found - would you like to create one? Yes
? Where would you like to create the dev config file? /Users/justinlu/airplane/node_test/airplane.dev.yaml
Created dev config file at /Users/justinlu/airplane/node_test/airplane.dev.yaml
Loaded dev config file at /Users/justinlu/airplane/node_test/airplane.dev.yaml
Discovering tasks and views...
Found 3 tasks:
- Country lookup
- Find user
- Generate report

Found 2 views:
- Admin panel
- test_view

Visit https://app.airplane.so:5000/editor?host=http://localhost:4000 for a development UI.
[Ctrl+C] to shutdown the local dev server.
^Ctrap: received "interrupt"
```

Moving dev config file into parent directory:

```
➜ mv ~/airplane/node_test/airplane.dev.yaml ~/airplane
➜ aplocal dev --editor ~/airplane/node_test
Loaded dev config file at /Users/justinlu/airplane/airplane.dev.yaml
Discovering tasks and views...
Found 3 tasks:
- Country lookup
- Find user
- Generate report

Found 2 views:
- Admin panel
- test_view

Visit https://app.airplane.so:5000/editor?host=http://localhost:4000 for a development UI.
[Ctrl+C] to shutdown the local dev server.
^Ctrap: received "interrupt"
```

Testing with no explicit dev root:

```
(⎈ |stage:airplane)➜  cli git:(justin/find-dev-config) ✗ aplocal dev --editor
Loaded dev config file at /Users/justinlu/go/src/github.com/airplanedev/cli/airplane.dev.yaml
...
```

2022-09-15 23:33 UTC, colinking requested changes

2022-09-15 23:33 UTC, colinking commented on cmd/airplane/tasks/dev/dev.go
> +						return err
wrap the error

2022-09-15 23:33 UTC, colinking commented on cmd/airplane/tasks/dev/dev.go
> +					// we want to return the directory itself in that case, and so we check if cfg.fileOrDir is a directory.
nice

2022-09-15 23:33 UTC, colinking commented on cmd/airplane/tasks/dev/dev.go
> +					cfg.devConfigPath = filepath.Join(devConfigDir, conf.DefaultDevConfigFileName)
Will this be an absolute path? If so, let's convert `devConfigPath` to an absolute path when explicitly set, too.

2022-09-15 23:33 UTC, colinking commented on cmd/airplane/tasks/dev/dev.go
> +					// Recursively search for dev config file from the dev dir until root.
Root is confusing (user root vs. task root)

```suggestion
					// Recursively search for dev config file, starting from the dev dir.
```

2022-09-15 23:33 UTC, colinking commented on cmd/airplane/tasks/dev/dev.go
> +			logger.Error("failed to stop local api server: %+v", err)
Why this change?

2022-09-15 23:33 UTC, colinking commented on pkg/conf/dev.go
> +// does not exist.
Hmm, IMO we shouldn't prompt the user to create a dev config file. Can we lazily create it? e.g. once a user tries to create a resource--via the CLI or via the UI -- then we should create it.

2022-09-15 23:33 UTC, colinking commented on pkg/conf/dev.go
> +		logger.Log("Using empty dev config")
Does this log mean anything to a user? Do we need it?

2022-09-15 23:33 UTC, colinking commented on pkg/conf/dev.go
> +		logger.Log("Loaded dev config file at %s", devConfigPath)
```suggestion
		logger.Log("Loaded dev config from %s", devConfigPath)
```

2022-09-16 02:13 UTC, calufornia commented on pkg/conf/dev.go
> +		logger.Log("Using empty dev config")
Changed to a debug log.

2022-09-16 02:14 UTC, calufornia commented on pkg/conf/dev.go
> +// does not exist.
Moved dev config file creation to `WriteDevConfig` - the first time that a resource/config is written to it it'll create the dev config file.

2022-09-16 02:37 UTC, calufornia commented on cmd/airplane/tasks/dev/config/set_resource/set_resource.go
> -	if err := conf.WriteDevConfig(devConfig); err != nil {
`SetResource` already persists the dev config file: https://github.com/airplanedev/cli/blob/4804dce5fb7ef11dd155253530dad58817253ce4/pkg/conf/dev.go#L71

2022-09-16 15:28 UTC, colinking approved these changes

2022-09-16 15:28 UTC, colinking commented on cmd/airplane/tasks/dev/config/config.go
> +		// the wrapper here.
good catch, this is confusing. I'd love to replace cobra with something easier/prettier at some point 😛

2022-09-16 15:28 UTC, colinking commented on cmd/airplane/tasks/dev/config/config.go
> -					path, err := conf.PromptDevConfigFileCreation(conf.DefaultDevConfigFileName)
This should still prompt to create the dev config, right? IIUC, looks like LoadDevConfigFile will error if it doesn't exist yet.

2022-09-16 15:28 UTC, colinking commented on pkg/conf/dev.go
>  	if err := os.WriteFile(config.Path, buf, 0600); err != nil {
```suggestion
	if err := os.WriteFile(config.Path, buf, 0644); err != nil {
```

2022-09-16 16:16 UTC, calufornia commented on cmd/airplane/tasks/dev/config/config.go
> +		// the wrapper here.
Ben mentioned https://github.com/segmentio/cli 🙂

2022-09-16 19:24 UTC, calufornia commented on cmd/airplane/tasks/dev/config/config.go
> -					path, err := conf.PromptDevConfigFileCreation(conf.DefaultDevConfigFileName)
It shouldn't error! We check `if !errors.Is(err, ErrMissing)` in `LoadDevConfigFile`, and only return an error in that case - otherwise, we return an empty dev config file with the default path so that it gets lazily created.

2022-09-16 19:31 UTC, merged