Make airplane dev use studio by default
airplanedev/cli pull request #732
Opened 2022-10-17 15:51 UTC by calufornia

## Description

Makes `airplane dev` use the studio by default - we keep the previous (headless) dev behavior around for now, but we should aim to remove that functionality sometime in the future. We mark `airplane views dev` as deprecated, and doing `airplane dev <view-dir>` will launch the studio now.

## Test plan
```
aplocal dev ~/airplane/node_test
11:36:18 Loaded dev config from /Users/justinlu/airplane/node_test/airplane.dev.yaml
Discovering tasks and views...
...
```
```
 aplocal dev --editor ~/airplane/node_test
Flag --editor has been deprecated, Launching the Studio is now the default behavior.
11:41:58 Loaded dev config from /Users/justinlu/airplane/node_test/airplane.dev.yaml
Discovering tasks and views...
```
```
aplocal views dev ~/airplane/node_test/admin_panel
Command "dev" is deprecated, Please use `airplane dev` instead.
...
```

2022-10-17 18:46 UTC, leeweisberger requested changes
Mostly confirming we didn't break `airplane views dev` behavior. Does this work? Does it open the studio?

2022-10-17 18:51 UTC, calufornia commented on cmd/airplane/tasks/dev/dev.go
> +			airplane dev --studio=false ./task.ts::<exportName> [-- <parameters...>] (for multiple tasks in one file in non-studio mode)
^cc @ameyakhare

2022-10-17 18:51 UTC, calufornia commented on cmd/airplane/tasks/dev/dev.go
> +			airplane dev --studio=false ./task.ts::<exportName> [-- <parameters...>] (for multiple tasks in one file in non-studio mode)
But I think it's something like...if you have two entrypoints in the same inline code config file

2022-10-17 18:53 UTC, leeweisberger commented on cmd/airplane/tasks/dev/dev.go
> +			airplane dev --studio=false ./task.ts::<exportName> [-- <parameters...>] (for multiple tasks in one file in non-studio mode)
Ok yeah that must be what it is. I think we should delete (see other comment). We should only document un-deprecated, common examples here

2022-10-17 18:53 UTC, ameyakhare commented on cmd/airplane/tasks/dev/dev.go
> +			airplane dev --studio=false ./task.ts::<exportName> [-- <parameters...>] (for multiple tasks in one file in non-studio mode)
you can have a bunch of things in the same file, so you have to specify the export name to run the right thing. once we get rid of local run in favor of studio, this wont be an issue anymore since studio properly discovers everything and then the user can just use the UI. I don't think we need to have these examples here

2022-10-17 18:57 UTC, calufornia commented on cmd/airplane/tasks/dev/dev.go
> -	fileInfo, err := os.Stat(cfg.fileOrDir)
Correct, `airplane views dev` still works (but there's a deprecation warning now if you attempt to use it). This logic just appears to be redirecting airplane dev -> airplane views dev if the argument is a view directory, which we will no longer do.

2022-10-17 19:00 UTC, leeweisberger commented on cmd/airplane/tasks/dev/dev.go
> +	cmd.Flags().BoolVar(&cfg.watch, "watch", true, "Watch for changes and apply updates to tasks, views, and workflows automatically.")
cc @kellymtrinh

2022-10-17 19:01 UTC, leeweisberger approved these changes

2022-10-17 19:01 UTC, calufornia commented on cmd/airplane/tasks/dev/dev.go
> +			airplane dev --studio=false ./task.ts::<exportName> [-- <parameters...>] (for multiple tasks in one file in non-studio mode)
Removed!

2022-10-17 19:04 UTC, kellymtrinh commented on cmd/airplane/tasks/dev/dev.go
> +	cmd.Flags().BoolVar(&cfg.watch, "watch", true, "Watch for changes and apply updates to tasks, views, and workflows automatically.")
How do we feel about deleting the `watch` flag and having a `--no-watch` flag to turn it off instead? 
I can open that change!

2022-10-18 05:46 UTC, calufornia commented on cmd/airplane/tasks/dev/dev.go
> +	cmd.Flags().BoolVar(&cfg.watch, "watch", true, "Watch for changes and apply updates to tasks, views, and workflows automatically.")
Sure! I can also include it in this PR, since we're turning it on by default here now.

2022-10-20 22:14 UTC, merged