When initializing a task, write node version to airplane.config.yaml
airplanedev/cli pull request #756
Opened 2022-10-27 14:55 UTC by leeweisberger

## Description
When creating a new task, create a new airplane.config.yaml and write the node version there
When there is already an airplane.config.yaml with no node version, update that airplane.config.yaml with the correct node version
When there is already an airplane.config.yaml or package.json with a conflicting node version, do nothing and warn

## Test plan
Manually tested all of the above cases

2022-10-27 17:03 UTC, leeweisberger commented on pkg/node/node.go
> +func CreatePackageJSON(directory string, packageJSONOptions PackageJSONOptions) error {
This function is just a refactor. No functionality change.

2022-10-27 19:56 UTC, ameyakhare requested changes
some open questions

2022-10-27 19:56 UTC, ameyakhare commented on cmd/airplane/tasks/initcmd/init.go
> +		if err := node.CreateAirplaneConfig(cwd, isNew, deployconfig.AirplaneConfig{
what does isNew do here?

2022-10-27 19:56 UTC, ameyakhare commented on cmd/airplane/tasks/initcmd/init.go
> +		if err := node.CreateAirplaneConfig(cwd, isNew, deployconfig.AirplaneConfig{
shouldnt we not be creating this if it already exists?

2022-10-27 19:56 UTC, ameyakhare commented on pkg/node/node.go
> +func mergeStructsRecursively(dest, src map[string]interface{}) {
nit: these arent really structs so if you want to generalize, make it mergeMapsRecusively

2022-10-27 19:56 UTC, ameyakhare commented on cmd/airplane/tasks/initcmd/init.go
> +		if err := node.CreateAirplaneConfig(cwd, isNew, deployconfig.AirplaneConfig{
nvm, it looks like CreateAirplaneConfig checks if there is already another one, a little confusing though imo based on the function name (maybe CreateOrMergeAirplaneConfig? idk)

2022-10-28 00:15 UTC, leeweisberger commented on cmd/airplane/tasks/initcmd/init.go
> +		if err := node.CreateAirplaneConfig(cwd, isNew, deployconfig.AirplaneConfig{
I updated the code to remove it. Don't think it's necessary

2022-10-28 00:15 UTC, leeweisberger commented on cmd/airplane/tasks/initcmd/init.go
> +		if err := node.CreateAirplaneConfig(cwd, isNew, deployconfig.AirplaneConfig{
Yeah updated

2022-10-31 19:48 UTC, ameyakhare approved these changes
nice

2022-10-31 19:58 UTC, merged