Dynamically assign studio port
airplanedev/cli pull request #870
Opened 2022-12-22 00:08 UTC by calufornia

## Description

If a `--port` option is not provided, the studio will attempt to bind to port 4000. This is problematic if another process is already bound to this port, and the user will most likely run into this if they attempt to spin up multiple studio sessions. Instead, we start at port 4000 and incrementally try to find an open port.

## Test plan
Tested by spinning up two instances of the studio, and verified that the second was bound to port 4001.

2022-12-22 00:18 UTC, calufornia commented on cmd/airplane/tasks/dev/server.go
> +		conn, _ := net.DialTimeout("tcp", fmt.Sprintf(":%d", port), time.Second)
We can also do this with `net.Listen`, but this causes an [inconvenient popup to occur on MacOS](https://apple.stackexchange.com/questions/393715/do-you-want-the-application-main-to-accept-incoming-network-connections-pop).

2022-12-22 18:07 UTC, colinking requested changes

2022-12-22 18:07 UTC, colinking commented on cmd/airplane/tasks/dev/server.go
> +		conn, _ := net.DialTimeout("tcp", fmt.Sprintf(":%d", port), time.Second)
On unix systems, you should be able to do `:0` to automatically connect to a free port. Should be much more efficient.

2022-12-22 18:09 UTC, colinking requested changes

2022-12-22 18:09 UTC, colinking commented on cmd/airplane/tasks/dev/server.go
> +	studioURL := fmt.Sprintf("%s/studio?__airplane_host=http://localhost:%d&__env=%s", appURL, port, remoteEnv.Slug)
Unrelated, but could this have been more concise? Did we expand this just because of the SSRF issue? Could we have done `?_port=4000` (which assumes `localhost`) and remote studio could then optionally set `_host` instead? (or does remote studio even need to set a host?)

2022-12-22 18:09 UTC, colinking commented on cmd/airplane/tasks/dev/server.go
> +		conn, _ := net.DialTimeout("tcp", fmt.Sprintf(":%d", port), time.Second)
Requesting changes just b/c I'm worried this could be slow! If that doesn't work, one idea would be to pick a less common port than `4000` to start from.

2022-12-22 18:20 UTC, calufornia commented on cmd/airplane/tasks/dev/server.go
> +		conn, _ := net.DialTimeout("tcp", fmt.Sprintf(":%d", port), time.Second)
I thought it would be nice to do what Vite did, where it incrementally tries to find a port, but I can also just have the system find one! Thought it might be nice for people to "associate" Studio with 400x ports, but those might be more popular than Vite's (5173)

2022-12-22 18:31 UTC, calufornia commented on cmd/airplane/tasks/dev/server.go
> +	studioURL := fmt.Sprintf("%s/studio?__airplane_host=http://localhost:%d&__env=%s", appURL, port, remoteEnv.Slug)
We changed from `host` -> `__airplane_host` since it conflicted I think it conflicted with Views (cc @zhan-airplane for the exact issue), not related to SSRF. I think we could do `__airplane_port=4000`

2022-12-22 18:33 UTC, colinking commented on cmd/airplane/tasks/dev/server.go
> +	studioURL := fmt.Sprintf("%s/studio?__airplane_host=http://localhost:%d&__env=%s", appURL, port, remoteEnv.Slug)
Huh, what does it conflict with? I know on the task page we have arbitrary URL params from the user's parameter slugs, but that's why we have added the underscores in the past. `__port` would presumably be enough.

2022-12-22 18:43 UTC, calufornia commented on cmd/airplane/tasks/dev/server.go
> +	studioURL := fmt.Sprintf("%s/studio?__airplane_host=http://localhost:%d&__env=%s", appURL, port, remoteEnv.Slug)
From what I understand, this is to avoid conflict with a user-supplied query parameter called `host` (e.g. https://docs.airplane.dev/views/routing#reading-parameters). But yeah `_port` or `__port` should be enough to not conflict too.

2022-12-22 18:45 UTC, zhan-airplane commented on cmd/airplane/tasks/dev/server.go
> +	studioURL := fmt.Sprintf("%s/studio?__airplane_host=http://localhost:%d&__env=%s", appURL, port, remoteEnv.Slug)
^ yup it was to avoid user parameter slug conflicts. For `__airplane_host`, I erred on the side of more verbosity to avoid potential conflicts (e.g. maybe users might also use underscores for some-reason-or-another)

2022-12-22 18:48 UTC, zhan-airplane commented on cmd/airplane/tasks/dev/server.go
> +	studioURL := fmt.Sprintf("%s/studio?__airplane_host=http://localhost:%d&__env=%s", appURL, port, remoteEnv.Slug)
I'm okay with renaming it to `__host` if you think that being concise is okay (and I guess on hindsight there's an argument with being consistent with how `__env` is named)

2022-12-22 21:14 UTC, calufornia commented
@colinking I ended up splitting up `server.Start` in two, since I didn't like how we would find a port, close the listener, only to the listen on that port again (which is also a potential race condition), so now the port allocation is implicitly part of `server.Start`. So first we call `Start` to start the dev server, and then we separately call `RegisterState` to populate its state. This means we can also trim most of the fields from `server.Options`, which was nearly identical to `State.

2022-12-23 14:05 UTC, colinking approved these changes
Nice cleanup!

2022-12-23 14:05 UTC, colinking commented on cmd/airplane/tasks/dev/dev.go
> +	cmd.Flags().IntVar(&cfg.port, "port", 0, "The port to start the local airplane api server on - defaults to a random open port.")
Can you confirm that port 0 also grabs an open port on Windows?

2022-12-23 18:20 UTC, calufornia commented on cmd/airplane/tasks/dev/dev.go
> +	cmd.Flags().IntVar(&cfg.port, "port", 0, "The port to start the local airplane api server on - defaults to a random open port.")
Works like a charm (ignoring the logger colors not working 🙂) : 
<img width="957" alt="image" src="https://user-images.githubusercontent.com/16730188/209390687-a39ede43-ef46-467f-923f-8f0209846641.png">

2022-12-23 21:06 UTC, merged