Add postcss config to .airplane-view if a view has a tailwind config
airplanedev/cli pull request #919
Opened 2023-01-24 05:58 UTC by geodn

## Description
Adds a postcss config to the .airplane-view dir if tailwind is detected in the root dir. This postcss config references the aforementioned tailwind config.

## Test plan
`go install ./cmd/airplane`
`airplane dev` with a view containing tailwind.config.js
verify that tailwind styles are applied

2023-01-24 06:34 UTC, calufornia requested changes

2023-01-24 06:34 UTC, calufornia commented on pkg/views/dev.go
> +		postcssConfigStr := `module.exports = {
Can you put this in an embedded file `postcss.config.js` instead?

2023-01-25 04:29 UTC, geodn commented on pkg/views/dev.go
> +		postcssConfigStr := `module.exports = {
With lib v0.5.144, this string is exported by libbuild - updated to use that

2023-01-25 15:18 UTC, calufornia approved these changes

2023-01-25 15:21 UTC, merged