Return remote run and outputs for apiint endpoints
airplanedev/cli pull request #928
Opened 2023-01-26 18:52 UTC by rose-huang

## Description
For the debug panel, we need the `/i/runs/get?runID=` and `/i/runs/getOutputs?runID=` endpoints to work. 

note: `/i/runs/get?runID=` still returns slightly diff info in studio than in our prod api so we are going to handle that in the web code

## Test plan
with changes in web:
https://user-images.githubusercontent.com/34196250/214923024-13049f75-b052-44c1-b9cb-e3de52a58680.mov

2023-01-26 22:03 UTC, rose-huang commented on pkg/api/types.go
> +	Parameters  *libapi.Parameters `json:"parameters"`
i just added the parameters field bc the web code wants it to show the parameter pills

2023-01-26 22:03 UTC, rose-huang commented on pkg/print/types.go
> +	Parameters  *libapi.Parameters `json:"parameters" yaml:"parameters"`
same also just adding parameters

2023-01-27 05:56 UTC, calufornia requested changes

2023-01-27 05:56 UTC, calufornia commented on pkg/server/apiint/apiint.go
> +func GetOutputsHandler(ctx context.Context, state *state.State, r *http.Request) (GetOutputsResponse, error) {
We have identical code in `apiext.go`—can you extract this code into a separate file (maybe into `/server/outputs.go`) and just use that function here?

2023-01-27 05:56 UTC, calufornia commented on pkg/server/apiint/apiint.go
>  func GetRunHandler(ctx context.Context, state *state.State, r *http.Request) (GetRunResponse, error) {
Can we modify the `/i/runs/get` endpoint to also return a `taskRevision` field (in addition to the `run` and `task` fields it currently returns)? I understand that this results in duplicate information in the response for now, but we can eventually remove the `task` field from the response so that it's just `run` and `taskRevision` and fully matches our prod API. We should be able to populate the TaskRevision struct from the Task struct, except for the task revision's ID and createdAt, but I don't think we're looking at those fields anyway so they can be generated on-the-fly. I think this will make the web changes a lot cleaner.

2023-01-27 21:57 UTC, rose-huang commented on pkg/server/apiint/apiint.go
>  func GetRunHandler(ctx context.Context, state *state.State, r *http.Request) (GetRunResponse, error) {
AD I left this as just run and task after adding task to the prod endpoint in https://github.com/airplanedev/airport/pull/3974/files

2023-01-30 15:47 UTC, calufornia approved these changes

2023-01-30 15:47 UTC, calufornia commented on pkg/server/apiint/apiint.go
> +		task, err := state.RemoteClient.GetTaskByID(ctx, remoteRun.TaskID)
`GetRun` should return the task now, right? Can we just modify `GetRunResponse` in `client.go`?

2023-01-30 18:34 UTC, rose-huang commented on pkg/server/apiint/apiint.go
> +		task, err := state.RemoteClient.GetTaskByID(ctx, remoteRun.TaskID)
@calufornia GetRun is hitting the external api endpoint which doesn't return the task rn 😅

2023-01-30 18:45 UTC, calufornia commented on pkg/server/apiint/apiint.go
> +		task, err := state.RemoteClient.GetTaskByID(ctx, remoteRun.TaskID)
Ah right...maybe should also modify the external endpoint at some point. But this looks fine to me now

2023-01-30 20:19 UTC, merged